package com.qheeshow.eway.service.model;

public class DocumentWithBLOBs extends Document {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.content
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.html
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private String html;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.content
	 * @return  the value of t_document.content
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.content
	 * @param content  the value for t_document.content
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.html
	 * @return  the value of t_document.html
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public String getHtml() {
		return html;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.html
	 * @param html  the value for t_document.html
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setHtml(String html) {
		this.html = html;
	}
}