package com.qheeshow.eway.service.model;

import com.qheeshow.eway.common.bean.BaseBean;
import java.util.Date;
import java.math.BigDecimal;

public class Document extends BaseBean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.id
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.title
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.summary
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private String summary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.index_pic
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private String indexPic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.ishead
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private Integer ishead;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.orderno
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private Integer orderno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.status
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.enroll_type
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private Integer enrollType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.enroll_price
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private BigDecimal enrollPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.create_time
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.create_user_id
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private Integer createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_document.publish_time
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	private Date publishTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.id
	 * @return  the value of t_document.id
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.id
	 * @param id  the value for t_document.id
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.title
	 * @return  the value of t_document.title
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.title
	 * @param title  the value for t_document.title
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.summary
	 * @return  the value of t_document.summary
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public String getSummary() {
		return summary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.summary
	 * @param summary  the value for t_document.summary
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setSummary(String summary) {
		this.summary = summary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.index_pic
	 * @return  the value of t_document.index_pic
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public String getIndexPic() {
		return indexPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.index_pic
	 * @param indexPic  the value for t_document.index_pic
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setIndexPic(String indexPic) {
		this.indexPic = indexPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.ishead
	 * @return  the value of t_document.ishead
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public Integer getIshead() {
		return ishead;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.ishead
	 * @param ishead  the value for t_document.ishead
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setIshead(Integer ishead) {
		this.ishead = ishead;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.orderno
	 * @return  the value of t_document.orderno
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public Integer getOrderno() {
		return orderno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.orderno
	 * @param orderno  the value for t_document.orderno
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setOrderno(Integer orderno) {
		this.orderno = orderno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.status
	 * @return  the value of t_document.status
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.status
	 * @param status  the value for t_document.status
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.enroll_type
	 * @return  the value of t_document.enroll_type
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public Integer getEnrollType() {
		return enrollType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.enroll_type
	 * @param enrollType  the value for t_document.enroll_type
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setEnrollType(Integer enrollType) {
		this.enrollType = enrollType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.enroll_price
	 * @return  the value of t_document.enroll_price
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public BigDecimal getEnrollPrice() {
		return enrollPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.enroll_price
	 * @param enrollPrice  the value for t_document.enroll_price
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setEnrollPrice(BigDecimal enrollPrice) {
		this.enrollPrice = enrollPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.create_time
	 * @return  the value of t_document.create_time
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.create_time
	 * @param createTime  the value for t_document.create_time
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.create_user_id
	 * @return  the value of t_document.create_user_id
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public Integer getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.create_user_id
	 * @param createUserId  the value for t_document.create_user_id
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_document.publish_time
	 * @return  the value of t_document.publish_time
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public Date getPublishTime() {
		return publishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_document.publish_time
	 * @param publishTime  the value for t_document.publish_time
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}
}