package com.qheeshow.eway.service.model;

import com.qheeshow.eway.common.bean.BaseBean;
import java.util.Date;

public class Document extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer docid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCCHANNEL
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer docchannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCVERSION
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer docversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCTYPE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer doctype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCTITLE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String doctitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCSOURCE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer docsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCSECURITY
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer docsecurity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCSTATUS
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer docstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCKIND
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer dockind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCABSTRACT
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String docabstract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCKEYWORDS
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String dockeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCRELWORDS
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String docrelwords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCPEOPLE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String docpeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCPLACE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String docplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCAUTHOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String docauthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCEDITOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String doceditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCAUDITOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String docauditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCOUTUPID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer docoutupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCVALID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Date docvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCPUBURL
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String docpuburl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCPUBTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Date docpubtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCRELTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Date docreltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.CRUSER
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String cruser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.CRTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Date crtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCWORDSCOUNT
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer docwordscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCPRO
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer docpro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.RIGHTDEFINED
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Short rightdefined;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.TITLECOLOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String titlecolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.TEMPLATEID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.SCHEDULE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer schedule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCNO
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String docno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCFLAG
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer docflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.EDITOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.ATTRIBUTE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String attribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.HITSCOUNT
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer hitscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.SUBDOCTITLE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String subdoctitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.ATTACHPIC
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Short attachpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCLINK
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String doclink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCFILENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String docfilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCFROMVERSION
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer docfromversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.OPERTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Date opertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.OPERUSER
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String operuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.FLOWOPERATIONMARK
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String flowoperationmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.FLOWPREOPERATIONMARK
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String flowpreoperationmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.FLOWOPERATIONMASKENUM
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String flowoperationmaskenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCSOURCENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String docsourcename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCLINKTO
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String doclinkto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCMIRRORTO
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String docmirrorto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.RANDOMSERIAL
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String randomserial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.POSTUSER
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String postuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.ISPAGEIMG
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Byte ispageimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.PUBLISHDATE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String publishdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.PAGENUM
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String pagenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.PAGENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String pagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.PDFFILENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String pdffilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.PAGEIMAGEFILENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String pageimagefilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.MAP
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String map;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.YINTI
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String yinti;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.SITEID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer siteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.SRCSITEID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer srcsiteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCFIRSTPUBTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Date docfirstpubtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.NODEID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer nodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.ORDERID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.CRDEPT
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String crdept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCFORM
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer docform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.DOCLEVEL
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private Integer doclevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument.olddocpuburl
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    private String olddocpuburl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCID
     *
     * @return the value of wcmdocument.DOCID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDocid() {
        return docid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCID
     *
     * @param docid the value for wcmdocument.DOCID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocid(Integer docid) {
        this.docid = docid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCCHANNEL
     *
     * @return the value of wcmdocument.DOCCHANNEL
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDocchannel() {
        return docchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCCHANNEL
     *
     * @param docchannel the value for wcmdocument.DOCCHANNEL
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocchannel(Integer docchannel) {
        this.docchannel = docchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCVERSION
     *
     * @return the value of wcmdocument.DOCVERSION
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDocversion() {
        return docversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCVERSION
     *
     * @param docversion the value for wcmdocument.DOCVERSION
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocversion(Integer docversion) {
        this.docversion = docversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCTYPE
     *
     * @return the value of wcmdocument.DOCTYPE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDoctype() {
        return doctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCTYPE
     *
     * @param doctype the value for wcmdocument.DOCTYPE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDoctype(Integer doctype) {
        this.doctype = doctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCTITLE
     *
     * @return the value of wcmdocument.DOCTITLE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDoctitle() {
        return doctitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCTITLE
     *
     * @param doctitle the value for wcmdocument.DOCTITLE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDoctitle(String doctitle) {
        this.doctitle = doctitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCSOURCE
     *
     * @return the value of wcmdocument.DOCSOURCE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDocsource() {
        return docsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCSOURCE
     *
     * @param docsource the value for wcmdocument.DOCSOURCE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocsource(Integer docsource) {
        this.docsource = docsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCSECURITY
     *
     * @return the value of wcmdocument.DOCSECURITY
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDocsecurity() {
        return docsecurity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCSECURITY
     *
     * @param docsecurity the value for wcmdocument.DOCSECURITY
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocsecurity(Integer docsecurity) {
        this.docsecurity = docsecurity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCSTATUS
     *
     * @return the value of wcmdocument.DOCSTATUS
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDocstatus() {
        return docstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCSTATUS
     *
     * @param docstatus the value for wcmdocument.DOCSTATUS
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocstatus(Integer docstatus) {
        this.docstatus = docstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCKIND
     *
     * @return the value of wcmdocument.DOCKIND
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDockind() {
        return dockind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCKIND
     *
     * @param dockind the value for wcmdocument.DOCKIND
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDockind(Integer dockind) {
        this.dockind = dockind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCABSTRACT
     *
     * @return the value of wcmdocument.DOCABSTRACT
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDocabstract() {
        return docabstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCABSTRACT
     *
     * @param docabstract the value for wcmdocument.DOCABSTRACT
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocabstract(String docabstract) {
        this.docabstract = docabstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCKEYWORDS
     *
     * @return the value of wcmdocument.DOCKEYWORDS
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDockeywords() {
        return dockeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCKEYWORDS
     *
     * @param dockeywords the value for wcmdocument.DOCKEYWORDS
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDockeywords(String dockeywords) {
        this.dockeywords = dockeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCRELWORDS
     *
     * @return the value of wcmdocument.DOCRELWORDS
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDocrelwords() {
        return docrelwords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCRELWORDS
     *
     * @param docrelwords the value for wcmdocument.DOCRELWORDS
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocrelwords(String docrelwords) {
        this.docrelwords = docrelwords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCPEOPLE
     *
     * @return the value of wcmdocument.DOCPEOPLE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDocpeople() {
        return docpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCPEOPLE
     *
     * @param docpeople the value for wcmdocument.DOCPEOPLE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocpeople(String docpeople) {
        this.docpeople = docpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCPLACE
     *
     * @return the value of wcmdocument.DOCPLACE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDocplace() {
        return docplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCPLACE
     *
     * @param docplace the value for wcmdocument.DOCPLACE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocplace(String docplace) {
        this.docplace = docplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCAUTHOR
     *
     * @return the value of wcmdocument.DOCAUTHOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDocauthor() {
        return docauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCAUTHOR
     *
     * @param docauthor the value for wcmdocument.DOCAUTHOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocauthor(String docauthor) {
        this.docauthor = docauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCEDITOR
     *
     * @return the value of wcmdocument.DOCEDITOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDoceditor() {
        return doceditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCEDITOR
     *
     * @param doceditor the value for wcmdocument.DOCEDITOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDoceditor(String doceditor) {
        this.doceditor = doceditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCAUDITOR
     *
     * @return the value of wcmdocument.DOCAUDITOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDocauditor() {
        return docauditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCAUDITOR
     *
     * @param docauditor the value for wcmdocument.DOCAUDITOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocauditor(String docauditor) {
        this.docauditor = docauditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCOUTUPID
     *
     * @return the value of wcmdocument.DOCOUTUPID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDocoutupid() {
        return docoutupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCOUTUPID
     *
     * @param docoutupid the value for wcmdocument.DOCOUTUPID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocoutupid(Integer docoutupid) {
        this.docoutupid = docoutupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCVALID
     *
     * @return the value of wcmdocument.DOCVALID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Date getDocvalid() {
        return docvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCVALID
     *
     * @param docvalid the value for wcmdocument.DOCVALID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocvalid(Date docvalid) {
        this.docvalid = docvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCPUBURL
     *
     * @return the value of wcmdocument.DOCPUBURL
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDocpuburl() {
        return docpuburl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCPUBURL
     *
     * @param docpuburl the value for wcmdocument.DOCPUBURL
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocpuburl(String docpuburl) {
        this.docpuburl = docpuburl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCPUBTIME
     *
     * @return the value of wcmdocument.DOCPUBTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Date getDocpubtime() {
        return docpubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCPUBTIME
     *
     * @param docpubtime the value for wcmdocument.DOCPUBTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocpubtime(Date docpubtime) {
        this.docpubtime = docpubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCRELTIME
     *
     * @return the value of wcmdocument.DOCRELTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Date getDocreltime() {
        return docreltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCRELTIME
     *
     * @param docreltime the value for wcmdocument.DOCRELTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocreltime(Date docreltime) {
        this.docreltime = docreltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.CRUSER
     *
     * @return the value of wcmdocument.CRUSER
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getCruser() {
        return cruser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.CRUSER
     *
     * @param cruser the value for wcmdocument.CRUSER
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setCruser(String cruser) {
        this.cruser = cruser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.CRTIME
     *
     * @return the value of wcmdocument.CRTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Date getCrtime() {
        return crtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.CRTIME
     *
     * @param crtime the value for wcmdocument.CRTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setCrtime(Date crtime) {
        this.crtime = crtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCWORDSCOUNT
     *
     * @return the value of wcmdocument.DOCWORDSCOUNT
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDocwordscount() {
        return docwordscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCWORDSCOUNT
     *
     * @param docwordscount the value for wcmdocument.DOCWORDSCOUNT
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocwordscount(Integer docwordscount) {
        this.docwordscount = docwordscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCPRO
     *
     * @return the value of wcmdocument.DOCPRO
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDocpro() {
        return docpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCPRO
     *
     * @param docpro the value for wcmdocument.DOCPRO
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocpro(Integer docpro) {
        this.docpro = docpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.RIGHTDEFINED
     *
     * @return the value of wcmdocument.RIGHTDEFINED
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Short getRightdefined() {
        return rightdefined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.RIGHTDEFINED
     *
     * @param rightdefined the value for wcmdocument.RIGHTDEFINED
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setRightdefined(Short rightdefined) {
        this.rightdefined = rightdefined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.TITLECOLOR
     *
     * @return the value of wcmdocument.TITLECOLOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getTitlecolor() {
        return titlecolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.TITLECOLOR
     *
     * @param titlecolor the value for wcmdocument.TITLECOLOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setTitlecolor(String titlecolor) {
        this.titlecolor = titlecolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.TEMPLATEID
     *
     * @return the value of wcmdocument.TEMPLATEID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.TEMPLATEID
     *
     * @param templateid the value for wcmdocument.TEMPLATEID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.SCHEDULE
     *
     * @return the value of wcmdocument.SCHEDULE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getSchedule() {
        return schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.SCHEDULE
     *
     * @param schedule the value for wcmdocument.SCHEDULE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setSchedule(Integer schedule) {
        this.schedule = schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCNO
     *
     * @return the value of wcmdocument.DOCNO
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDocno() {
        return docno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCNO
     *
     * @param docno the value for wcmdocument.DOCNO
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocno(String docno) {
        this.docno = docno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCFLAG
     *
     * @return the value of wcmdocument.DOCFLAG
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDocflag() {
        return docflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCFLAG
     *
     * @param docflag the value for wcmdocument.DOCFLAG
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocflag(Integer docflag) {
        this.docflag = docflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.EDITOR
     *
     * @return the value of wcmdocument.EDITOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.EDITOR
     *
     * @param editor the value for wcmdocument.EDITOR
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setEditor(String editor) {
        this.editor = editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.ATTRIBUTE
     *
     * @return the value of wcmdocument.ATTRIBUTE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.ATTRIBUTE
     *
     * @param attribute the value for wcmdocument.ATTRIBUTE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.HITSCOUNT
     *
     * @return the value of wcmdocument.HITSCOUNT
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getHitscount() {
        return hitscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.HITSCOUNT
     *
     * @param hitscount the value for wcmdocument.HITSCOUNT
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setHitscount(Integer hitscount) {
        this.hitscount = hitscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.SUBDOCTITLE
     *
     * @return the value of wcmdocument.SUBDOCTITLE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getSubdoctitle() {
        return subdoctitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.SUBDOCTITLE
     *
     * @param subdoctitle the value for wcmdocument.SUBDOCTITLE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setSubdoctitle(String subdoctitle) {
        this.subdoctitle = subdoctitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.ATTACHPIC
     *
     * @return the value of wcmdocument.ATTACHPIC
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Short getAttachpic() {
        return attachpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.ATTACHPIC
     *
     * @param attachpic the value for wcmdocument.ATTACHPIC
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setAttachpic(Short attachpic) {
        this.attachpic = attachpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCLINK
     *
     * @return the value of wcmdocument.DOCLINK
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDoclink() {
        return doclink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCLINK
     *
     * @param doclink the value for wcmdocument.DOCLINK
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDoclink(String doclink) {
        this.doclink = doclink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCFILENAME
     *
     * @return the value of wcmdocument.DOCFILENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDocfilename() {
        return docfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCFILENAME
     *
     * @param docfilename the value for wcmdocument.DOCFILENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocfilename(String docfilename) {
        this.docfilename = docfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCFROMVERSION
     *
     * @return the value of wcmdocument.DOCFROMVERSION
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDocfromversion() {
        return docfromversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCFROMVERSION
     *
     * @param docfromversion the value for wcmdocument.DOCFROMVERSION
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocfromversion(Integer docfromversion) {
        this.docfromversion = docfromversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.OPERTIME
     *
     * @return the value of wcmdocument.OPERTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Date getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.OPERTIME
     *
     * @param opertime the value for wcmdocument.OPERTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setOpertime(Date opertime) {
        this.opertime = opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.OPERUSER
     *
     * @return the value of wcmdocument.OPERUSER
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getOperuser() {
        return operuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.OPERUSER
     *
     * @param operuser the value for wcmdocument.OPERUSER
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setOperuser(String operuser) {
        this.operuser = operuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.FLOWOPERATIONMARK
     *
     * @return the value of wcmdocument.FLOWOPERATIONMARK
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getFlowoperationmark() {
        return flowoperationmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.FLOWOPERATIONMARK
     *
     * @param flowoperationmark the value for wcmdocument.FLOWOPERATIONMARK
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setFlowoperationmark(String flowoperationmark) {
        this.flowoperationmark = flowoperationmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.FLOWPREOPERATIONMARK
     *
     * @return the value of wcmdocument.FLOWPREOPERATIONMARK
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getFlowpreoperationmark() {
        return flowpreoperationmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.FLOWPREOPERATIONMARK
     *
     * @param flowpreoperationmark the value for wcmdocument.FLOWPREOPERATIONMARK
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setFlowpreoperationmark(String flowpreoperationmark) {
        this.flowpreoperationmark = flowpreoperationmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.FLOWOPERATIONMASKENUM
     *
     * @return the value of wcmdocument.FLOWOPERATIONMASKENUM
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getFlowoperationmaskenum() {
        return flowoperationmaskenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.FLOWOPERATIONMASKENUM
     *
     * @param flowoperationmaskenum the value for wcmdocument.FLOWOPERATIONMASKENUM
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setFlowoperationmaskenum(String flowoperationmaskenum) {
        this.flowoperationmaskenum = flowoperationmaskenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCSOURCENAME
     *
     * @return the value of wcmdocument.DOCSOURCENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDocsourcename() {
        return docsourcename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCSOURCENAME
     *
     * @param docsourcename the value for wcmdocument.DOCSOURCENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocsourcename(String docsourcename) {
        this.docsourcename = docsourcename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCLINKTO
     *
     * @return the value of wcmdocument.DOCLINKTO
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDoclinkto() {
        return doclinkto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCLINKTO
     *
     * @param doclinkto the value for wcmdocument.DOCLINKTO
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDoclinkto(String doclinkto) {
        this.doclinkto = doclinkto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCMIRRORTO
     *
     * @return the value of wcmdocument.DOCMIRRORTO
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getDocmirrorto() {
        return docmirrorto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCMIRRORTO
     *
     * @param docmirrorto the value for wcmdocument.DOCMIRRORTO
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocmirrorto(String docmirrorto) {
        this.docmirrorto = docmirrorto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.RANDOMSERIAL
     *
     * @return the value of wcmdocument.RANDOMSERIAL
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getRandomserial() {
        return randomserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.RANDOMSERIAL
     *
     * @param randomserial the value for wcmdocument.RANDOMSERIAL
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setRandomserial(String randomserial) {
        this.randomserial = randomserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.POSTUSER
     *
     * @return the value of wcmdocument.POSTUSER
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getPostuser() {
        return postuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.POSTUSER
     *
     * @param postuser the value for wcmdocument.POSTUSER
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setPostuser(String postuser) {
        this.postuser = postuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.ISPAGEIMG
     *
     * @return the value of wcmdocument.ISPAGEIMG
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Byte getIspageimg() {
        return ispageimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.ISPAGEIMG
     *
     * @param ispageimg the value for wcmdocument.ISPAGEIMG
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setIspageimg(Byte ispageimg) {
        this.ispageimg = ispageimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.PUBLISHDATE
     *
     * @return the value of wcmdocument.PUBLISHDATE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getPublishdate() {
        return publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.PUBLISHDATE
     *
     * @param publishdate the value for wcmdocument.PUBLISHDATE
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setPublishdate(String publishdate) {
        this.publishdate = publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.PAGENUM
     *
     * @return the value of wcmdocument.PAGENUM
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getPagenum() {
        return pagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.PAGENUM
     *
     * @param pagenum the value for wcmdocument.PAGENUM
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setPagenum(String pagenum) {
        this.pagenum = pagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.PAGENAME
     *
     * @return the value of wcmdocument.PAGENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getPagename() {
        return pagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.PAGENAME
     *
     * @param pagename the value for wcmdocument.PAGENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setPagename(String pagename) {
        this.pagename = pagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.PDFFILENAME
     *
     * @return the value of wcmdocument.PDFFILENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getPdffilename() {
        return pdffilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.PDFFILENAME
     *
     * @param pdffilename the value for wcmdocument.PDFFILENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setPdffilename(String pdffilename) {
        this.pdffilename = pdffilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.PAGEIMAGEFILENAME
     *
     * @return the value of wcmdocument.PAGEIMAGEFILENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getPageimagefilename() {
        return pageimagefilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.PAGEIMAGEFILENAME
     *
     * @param pageimagefilename the value for wcmdocument.PAGEIMAGEFILENAME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setPageimagefilename(String pageimagefilename) {
        this.pageimagefilename = pageimagefilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.MAP
     *
     * @return the value of wcmdocument.MAP
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getMap() {
        return map;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.MAP
     *
     * @param map the value for wcmdocument.MAP
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setMap(String map) {
        this.map = map;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.YINTI
     *
     * @return the value of wcmdocument.YINTI
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getYinti() {
        return yinti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.YINTI
     *
     * @param yinti the value for wcmdocument.YINTI
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setYinti(String yinti) {
        this.yinti = yinti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.SITEID
     *
     * @return the value of wcmdocument.SITEID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.SITEID
     *
     * @param siteid the value for wcmdocument.SITEID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setSiteid(Integer siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.SRCSITEID
     *
     * @return the value of wcmdocument.SRCSITEID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getSrcsiteid() {
        return srcsiteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.SRCSITEID
     *
     * @param srcsiteid the value for wcmdocument.SRCSITEID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setSrcsiteid(Integer srcsiteid) {
        this.srcsiteid = srcsiteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCFIRSTPUBTIME
     *
     * @return the value of wcmdocument.DOCFIRSTPUBTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Date getDocfirstpubtime() {
        return docfirstpubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCFIRSTPUBTIME
     *
     * @param docfirstpubtime the value for wcmdocument.DOCFIRSTPUBTIME
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocfirstpubtime(Date docfirstpubtime) {
        this.docfirstpubtime = docfirstpubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.NODEID
     *
     * @return the value of wcmdocument.NODEID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getNodeid() {
        return nodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.NODEID
     *
     * @param nodeid the value for wcmdocument.NODEID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setNodeid(Integer nodeid) {
        this.nodeid = nodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.ORDERID
     *
     * @return the value of wcmdocument.ORDERID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.ORDERID
     *
     * @param orderid the value for wcmdocument.ORDERID
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.CRDEPT
     *
     * @return the value of wcmdocument.CRDEPT
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getCrdept() {
        return crdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.CRDEPT
     *
     * @param crdept the value for wcmdocument.CRDEPT
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setCrdept(String crdept) {
        this.crdept = crdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCFORM
     *
     * @return the value of wcmdocument.DOCFORM
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDocform() {
        return docform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCFORM
     *
     * @param docform the value for wcmdocument.DOCFORM
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDocform(Integer docform) {
        this.docform = docform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.DOCLEVEL
     *
     * @return the value of wcmdocument.DOCLEVEL
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public Integer getDoclevel() {
        return doclevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.DOCLEVEL
     *
     * @param doclevel the value for wcmdocument.DOCLEVEL
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setDoclevel(Integer doclevel) {
        this.doclevel = doclevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument.olddocpuburl
     *
     * @return the value of wcmdocument.olddocpuburl
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public String getOlddocpuburl() {
        return olddocpuburl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument.olddocpuburl
     *
     * @param olddocpuburl the value for wcmdocument.olddocpuburl
     *
     * @mbggenerated Sat Feb 25 14:07:41 CST 2017
     */
    public void setOlddocpuburl(String olddocpuburl) {
        this.olddocpuburl = olddocpuburl;
    }
}