package com.qheeshow.eway.service.model;

public class DocumentWithBLOBs extends Document {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wcmdocument.DOCCONTENT
	 * @mbggenerated  Sat Feb 25 14:07:41 CST 2017
	 */
	private String doccontent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wcmdocument.DOCHTMLCON
	 * @mbggenerated  Sat Feb 25 14:07:41 CST 2017
	 */
	private String dochtmlcon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wcmdocument.DOCPUBHTMLCON
	 * @mbggenerated  Sat Feb 25 14:07:41 CST 2017
	 */
	private String docpubhtmlcon;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wcmdocument.DOCCONTENT
	 * @return  the value of wcmdocument.DOCCONTENT
	 * @mbggenerated  Sat Feb 25 14:07:41 CST 2017
	 */
	public String getDoccontent() {
		return doccontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wcmdocument.DOCCONTENT
	 * @param doccontent  the value for wcmdocument.DOCCONTENT
	 * @mbggenerated  Sat Feb 25 14:07:41 CST 2017
	 */
	public void setDoccontent(String doccontent) {
		this.doccontent = doccontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wcmdocument.DOCHTMLCON
	 * @return  the value of wcmdocument.DOCHTMLCON
	 * @mbggenerated  Sat Feb 25 14:07:41 CST 2017
	 */
	public String getDochtmlcon() {
		return dochtmlcon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wcmdocument.DOCHTMLCON
	 * @param dochtmlcon  the value for wcmdocument.DOCHTMLCON
	 * @mbggenerated  Sat Feb 25 14:07:41 CST 2017
	 */
	public void setDochtmlcon(String dochtmlcon) {
		this.dochtmlcon = dochtmlcon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wcmdocument.DOCPUBHTMLCON
	 * @return  the value of wcmdocument.DOCPUBHTMLCON
	 * @mbggenerated  Sat Feb 25 14:07:41 CST 2017
	 */
	public String getDocpubhtmlcon() {
		return docpubhtmlcon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wcmdocument.DOCPUBHTMLCON
	 * @param docpubhtmlcon  the value for wcmdocument.DOCPUBHTMLCON
	 * @mbggenerated  Sat Feb 25 14:07:41 CST 2017
	 */
	public void setDocpubhtmlcon(String docpubhtmlcon) {
		this.docpubhtmlcon = docpubhtmlcon;
	}
}