package com.qheeshow.eway.service.model;

import com.qheeshow.eway.common.bean.BaseBean;
import java.math.BigDecimal;
import java.util.Date;

public class DocumentEnroll extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.id
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.user_id
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.user_name
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.document_id
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private Integer documentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.create_time
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.trade_no
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.transaction_type
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private Integer transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.transaction_no
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private String transactionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.pay_status
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.pay_time
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.pay_price
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private BigDecimal payPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.refund_status
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private Integer refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.refund_time
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private Date refundTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmdocument_enroll.refund_price
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    private BigDecimal refundPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.id
     *
     * @return the value of wcmdocument_enroll.id
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.id
     *
     * @param id the value for wcmdocument_enroll.id
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.user_id
     *
     * @return the value of wcmdocument_enroll.user_id
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.user_id
     *
     * @param userId the value for wcmdocument_enroll.user_id
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.user_name
     *
     * @return the value of wcmdocument_enroll.user_name
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.user_name
     *
     * @param userName the value for wcmdocument_enroll.user_name
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.document_id
     *
     * @return the value of wcmdocument_enroll.document_id
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.document_id
     *
     * @param documentId the value for wcmdocument_enroll.document_id
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.create_time
     *
     * @return the value of wcmdocument_enroll.create_time
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.create_time
     *
     * @param createTime the value for wcmdocument_enroll.create_time
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.trade_no
     *
     * @return the value of wcmdocument_enroll.trade_no
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.trade_no
     *
     * @param tradeNo the value for wcmdocument_enroll.trade_no
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.transaction_type
     *
     * @return the value of wcmdocument_enroll.transaction_type
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public Integer getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.transaction_type
     *
     * @param transactionType the value for wcmdocument_enroll.transaction_type
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setTransactionType(Integer transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.transaction_no
     *
     * @return the value of wcmdocument_enroll.transaction_no
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public String getTransactionNo() {
        return transactionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.transaction_no
     *
     * @param transactionNo the value for wcmdocument_enroll.transaction_no
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setTransactionNo(String transactionNo) {
        this.transactionNo = transactionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.pay_status
     *
     * @return the value of wcmdocument_enroll.pay_status
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.pay_status
     *
     * @param payStatus the value for wcmdocument_enroll.pay_status
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.pay_time
     *
     * @return the value of wcmdocument_enroll.pay_time
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.pay_time
     *
     * @param payTime the value for wcmdocument_enroll.pay_time
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.pay_price
     *
     * @return the value of wcmdocument_enroll.pay_price
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public BigDecimal getPayPrice() {
        return payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.pay_price
     *
     * @param payPrice the value for wcmdocument_enroll.pay_price
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setPayPrice(BigDecimal payPrice) {
        this.payPrice = payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.refund_status
     *
     * @return the value of wcmdocument_enroll.refund_status
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public Integer getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.refund_status
     *
     * @param refundStatus the value for wcmdocument_enroll.refund_status
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setRefundStatus(Integer refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.refund_time
     *
     * @return the value of wcmdocument_enroll.refund_time
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public Date getRefundTime() {
        return refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.refund_time
     *
     * @param refundTime the value for wcmdocument_enroll.refund_time
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setRefundTime(Date refundTime) {
        this.refundTime = refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmdocument_enroll.refund_price
     *
     * @return the value of wcmdocument_enroll.refund_price
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public BigDecimal getRefundPrice() {
        return refundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmdocument_enroll.refund_price
     *
     * @param refundPrice the value for wcmdocument_enroll.refund_price
     *
     * @mbggenerated Sat Feb 25 14:36:00 CST 2017
     */
    public void setRefundPrice(BigDecimal refundPrice) {
        this.refundPrice = refundPrice;
    }
}