package com.qheeshow.eway.service.model;

public class FileWithBLOBs extends File {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_file.original_path
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	private String originalPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_file.small_path
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	private String smallPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_file.original_name
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	private String originalName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_file.original_path
	 * @return  the value of t_file.original_path
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public String getOriginalPath() {
		return originalPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_file.original_path
	 * @param originalPath  the value for t_file.original_path
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public void setOriginalPath(String originalPath) {
		this.originalPath = originalPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_file.small_path
	 * @return  the value of t_file.small_path
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public String getSmallPath() {
		return smallPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_file.small_path
	 * @param smallPath  the value for t_file.small_path
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public void setSmallPath(String smallPath) {
		this.smallPath = smallPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_file.original_name
	 * @return  the value of t_file.original_name
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public String getOriginalName() {
		return originalName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_file.original_name
	 * @param originalName  the value for t_file.original_name
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public void setOriginalName(String originalName) {
		this.originalName = originalName;
	}
}