package com.qheeshow.eway.service.model;

import com.qheeshow.eway.common.bean.BaseBean;
import java.util.Date;

public class File extends BaseBean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_file.id
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_file.user_id
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_file.company_id
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	private Integer companyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_file.create_time
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_file.is_open
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	private Integer isOpen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_file.status
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_file.content_type
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	private String contentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_file.file_size
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	private Long fileSize;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_file.id
	 * @return  the value of t_file.id
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_file.id
	 * @param id  the value for t_file.id
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_file.user_id
	 * @return  the value of t_file.user_id
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_file.user_id
	 * @param userId  the value for t_file.user_id
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_file.company_id
	 * @return  the value of t_file.company_id
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public Integer getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_file.company_id
	 * @param companyId  the value for t_file.company_id
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_file.create_time
	 * @return  the value of t_file.create_time
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_file.create_time
	 * @param createTime  the value for t_file.create_time
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_file.is_open
	 * @return  the value of t_file.is_open
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public Integer getIsOpen() {
		return isOpen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_file.is_open
	 * @param isOpen  the value for t_file.is_open
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public void setIsOpen(Integer isOpen) {
		this.isOpen = isOpen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_file.status
	 * @return  the value of t_file.status
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_file.status
	 * @param status  the value for t_file.status
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_file.content_type
	 * @return  the value of t_file.content_type
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_file.content_type
	 * @param contentType  the value for t_file.content_type
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_file.file_size
	 * @return  the value of t_file.file_size
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public Long getFileSize() {
		return fileSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_file.file_size
	 * @param fileSize  the value for t_file.file_size
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}
}