package com.qheeshow.eway.service.model;

public class GoodsWithBLOBs extends Goods {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.goods_describe
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	private String goodsDescribe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.items
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	private String items;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.goods_describe
	 * @return  the value of t_goods.goods_describe
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public String getGoodsDescribe() {
		return goodsDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.goods_describe
	 * @param goodsDescribe  the value for t_goods.goods_describe
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public void setGoodsDescribe(String goodsDescribe) {
		this.goodsDescribe = goodsDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.items
	 * @return  the value of t_goods.items
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public String getItems() {
		return items;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.items
	 * @param items  the value for t_goods.items
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public void setItems(String items) {
		this.items = items;
	}
}