package com.qheeshow.eway.service.model;

import com.qheeshow.eway.common.bean.BaseBean;
import java.math.BigDecimal;
import java.util.Date;

public class Goods extends BaseBean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.id
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.title
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.price
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.order_num
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	private String orderNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.status
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.create_user_id
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	private Integer createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.create_time
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.discount_price
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	private BigDecimal discountPrice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.id
	 * @return  the value of t_goods.id
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.id
	 * @param id  the value for t_goods.id
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.title
	 * @return  the value of t_goods.title
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.title
	 * @param title  the value for t_goods.title
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.price
	 * @return  the value of t_goods.price
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.price
	 * @param price  the value for t_goods.price
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.order_num
	 * @return  the value of t_goods.order_num
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public String getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.order_num
	 * @param orderNum  the value for t_goods.order_num
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.status
	 * @return  the value of t_goods.status
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.status
	 * @param status  the value for t_goods.status
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.create_user_id
	 * @return  the value of t_goods.create_user_id
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public Integer getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.create_user_id
	 * @param createUserId  the value for t_goods.create_user_id
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.create_time
	 * @return  the value of t_goods.create_time
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.create_time
	 * @param createTime  the value for t_goods.create_time
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.discount_price
	 * @return  the value of t_goods.discount_price
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public BigDecimal getDiscountPrice() {
		return discountPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.discount_price
	 * @param discountPrice  the value for t_goods.discount_price
	 * @mbggenerated  Sun Feb 26 13:17:29 CST 2017
	 */
	public void setDiscountPrice(BigDecimal discountPrice) {
		this.discountPrice = discountPrice;
	}
}