package com.qheeshow.eway.service.model;

import com.qheeshow.eway.common.bean.BaseBean;
import java.math.BigDecimal;
import java.util.Date;

public class Investor extends BaseBean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.img
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private Integer img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.true_name
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private String trueName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.investor_type
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private Integer investorType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.company_name
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.company_rank
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private String companyRank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.wechat_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private String wechatId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.stage_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private Integer stageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.stage_name
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private String stageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.single_price_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private Integer singlePriceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.mobile
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.email
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.id_card
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private String idCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.business_card_positive
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private Integer businessCardPositive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.business_card_opposite
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private Integer businessCardOpposite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.personal_assets_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private Integer personalAssetsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.personal_assets
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private String personalAssets;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.status
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.user_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.create_time
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.id
	 * @return  the value of t_investor.id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.id
	 * @param id  the value for t_investor.id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.img
	 * @return  the value of t_investor.img
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public Integer getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.img
	 * @param img  the value for t_investor.img
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setImg(Integer img) {
		this.img = img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.true_name
	 * @return  the value of t_investor.true_name
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public String getTrueName() {
		return trueName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.true_name
	 * @param trueName  the value for t_investor.true_name
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setTrueName(String trueName) {
		this.trueName = trueName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.investor_type
	 * @return  the value of t_investor.investor_type
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public Integer getInvestorType() {
		return investorType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.investor_type
	 * @param investorType  the value for t_investor.investor_type
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setInvestorType(Integer investorType) {
		this.investorType = investorType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.company_name
	 * @return  the value of t_investor.company_name
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.company_name
	 * @param companyName  the value for t_investor.company_name
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.company_rank
	 * @return  the value of t_investor.company_rank
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public String getCompanyRank() {
		return companyRank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.company_rank
	 * @param companyRank  the value for t_investor.company_rank
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setCompanyRank(String companyRank) {
		this.companyRank = companyRank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.wechat_id
	 * @return  the value of t_investor.wechat_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public String getWechatId() {
		return wechatId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.wechat_id
	 * @param wechatId  the value for t_investor.wechat_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setWechatId(String wechatId) {
		this.wechatId = wechatId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.stage_id
	 * @return  the value of t_investor.stage_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public Integer getStageId() {
		return stageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.stage_id
	 * @param stageId  the value for t_investor.stage_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setStageId(Integer stageId) {
		this.stageId = stageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.stage_name
	 * @return  the value of t_investor.stage_name
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public String getStageName() {
		return stageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.stage_name
	 * @param stageName  the value for t_investor.stage_name
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setStageName(String stageName) {
		this.stageName = stageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.single_price_id
	 * @return  the value of t_investor.single_price_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public Integer getSinglePriceId() {
		return singlePriceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.single_price_id
	 * @param singlePriceId  the value for t_investor.single_price_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setSinglePriceId(Integer singlePriceId) {
		this.singlePriceId = singlePriceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.mobile
	 * @return  the value of t_investor.mobile
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.mobile
	 * @param mobile  the value for t_investor.mobile
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.email
	 * @return  the value of t_investor.email
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.email
	 * @param email  the value for t_investor.email
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.id_card
	 * @return  the value of t_investor.id_card
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public String getIdCard() {
		return idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.id_card
	 * @param idCard  the value for t_investor.id_card
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.business_card_positive
	 * @return  the value of t_investor.business_card_positive
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public Integer getBusinessCardPositive() {
		return businessCardPositive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.business_card_positive
	 * @param businessCardPositive  the value for t_investor.business_card_positive
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setBusinessCardPositive(Integer businessCardPositive) {
		this.businessCardPositive = businessCardPositive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.business_card_opposite
	 * @return  the value of t_investor.business_card_opposite
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public Integer getBusinessCardOpposite() {
		return businessCardOpposite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.business_card_opposite
	 * @param businessCardOpposite  the value for t_investor.business_card_opposite
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setBusinessCardOpposite(Integer businessCardOpposite) {
		this.businessCardOpposite = businessCardOpposite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.personal_assets_id
	 * @return  the value of t_investor.personal_assets_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public Integer getPersonalAssetsId() {
		return personalAssetsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.personal_assets_id
	 * @param personalAssetsId  the value for t_investor.personal_assets_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setPersonalAssetsId(Integer personalAssetsId) {
		this.personalAssetsId = personalAssetsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.personal_assets
	 * @return  the value of t_investor.personal_assets
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public String getPersonalAssets() {
		return personalAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.personal_assets
	 * @param personalAssets  the value for t_investor.personal_assets
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setPersonalAssets(String personalAssets) {
		this.personalAssets = personalAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.status
	 * @return  the value of t_investor.status
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.status
	 * @param status  the value for t_investor.status
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.user_id
	 * @return  the value of t_investor.user_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.user_id
	 * @param userId  the value for t_investor.user_id
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.create_time
	 * @return  the value of t_investor.create_time
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.create_time
	 * @param createTime  the value for t_investor.create_time
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}