package com.qheeshow.eway.service.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class InvestorExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public InvestorExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andImgIsNull() {
			addCriterion("img is null");
			return (Criteria) this;
		}

		public Criteria andImgIsNotNull() {
			addCriterion("img is not null");
			return (Criteria) this;
		}

		public Criteria andImgEqualTo(Integer value) {
			addCriterion("img =", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgNotEqualTo(Integer value) {
			addCriterion("img <>", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgGreaterThan(Integer value) {
			addCriterion("img >", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgGreaterThanOrEqualTo(Integer value) {
			addCriterion("img >=", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgLessThan(Integer value) {
			addCriterion("img <", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgLessThanOrEqualTo(Integer value) {
			addCriterion("img <=", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgIn(List<Integer> values) {
			addCriterion("img in", values, "img");
			return (Criteria) this;
		}

		public Criteria andImgNotIn(List<Integer> values) {
			addCriterion("img not in", values, "img");
			return (Criteria) this;
		}

		public Criteria andImgBetween(Integer value1, Integer value2) {
			addCriterion("img between", value1, value2, "img");
			return (Criteria) this;
		}

		public Criteria andImgNotBetween(Integer value1, Integer value2) {
			addCriterion("img not between", value1, value2, "img");
			return (Criteria) this;
		}

		public Criteria andTrueNameIsNull() {
			addCriterion("true_name is null");
			return (Criteria) this;
		}

		public Criteria andTrueNameIsNotNull() {
			addCriterion("true_name is not null");
			return (Criteria) this;
		}

		public Criteria andTrueNameEqualTo(String value) {
			addCriterion("true_name =", value, "trueName");
			return (Criteria) this;
		}

		public Criteria andTrueNameNotEqualTo(String value) {
			addCriterion("true_name <>", value, "trueName");
			return (Criteria) this;
		}

		public Criteria andTrueNameGreaterThan(String value) {
			addCriterion("true_name >", value, "trueName");
			return (Criteria) this;
		}

		public Criteria andTrueNameGreaterThanOrEqualTo(String value) {
			addCriterion("true_name >=", value, "trueName");
			return (Criteria) this;
		}

		public Criteria andTrueNameLessThan(String value) {
			addCriterion("true_name <", value, "trueName");
			return (Criteria) this;
		}

		public Criteria andTrueNameLessThanOrEqualTo(String value) {
			addCriterion("true_name <=", value, "trueName");
			return (Criteria) this;
		}

		public Criteria andTrueNameLike(String value) {
			addCriterion("true_name like", value, "trueName");
			return (Criteria) this;
		}

		public Criteria andTrueNameNotLike(String value) {
			addCriterion("true_name not like", value, "trueName");
			return (Criteria) this;
		}

		public Criteria andTrueNameIn(List<String> values) {
			addCriterion("true_name in", values, "trueName");
			return (Criteria) this;
		}

		public Criteria andTrueNameNotIn(List<String> values) {
			addCriterion("true_name not in", values, "trueName");
			return (Criteria) this;
		}

		public Criteria andTrueNameBetween(String value1, String value2) {
			addCriterion("true_name between", value1, value2, "trueName");
			return (Criteria) this;
		}

		public Criteria andTrueNameNotBetween(String value1, String value2) {
			addCriterion("true_name not between", value1, value2, "trueName");
			return (Criteria) this;
		}

		public Criteria andInvestorTypeIsNull() {
			addCriterion("investor_type is null");
			return (Criteria) this;
		}

		public Criteria andInvestorTypeIsNotNull() {
			addCriterion("investor_type is not null");
			return (Criteria) this;
		}

		public Criteria andInvestorTypeEqualTo(Integer value) {
			addCriterion("investor_type =", value, "investorType");
			return (Criteria) this;
		}

		public Criteria andInvestorTypeNotEqualTo(Integer value) {
			addCriterion("investor_type <>", value, "investorType");
			return (Criteria) this;
		}

		public Criteria andInvestorTypeGreaterThan(Integer value) {
			addCriterion("investor_type >", value, "investorType");
			return (Criteria) this;
		}

		public Criteria andInvestorTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("investor_type >=", value, "investorType");
			return (Criteria) this;
		}

		public Criteria andInvestorTypeLessThan(Integer value) {
			addCriterion("investor_type <", value, "investorType");
			return (Criteria) this;
		}

		public Criteria andInvestorTypeLessThanOrEqualTo(Integer value) {
			addCriterion("investor_type <=", value, "investorType");
			return (Criteria) this;
		}

		public Criteria andInvestorTypeIn(List<Integer> values) {
			addCriterion("investor_type in", values, "investorType");
			return (Criteria) this;
		}

		public Criteria andInvestorTypeNotIn(List<Integer> values) {
			addCriterion("investor_type not in", values, "investorType");
			return (Criteria) this;
		}

		public Criteria andInvestorTypeBetween(Integer value1, Integer value2) {
			addCriterion("investor_type between", value1, value2, "investorType");
			return (Criteria) this;
		}

		public Criteria andInvestorTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("investor_type not between", value1, value2, "investorType");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNull() {
			addCriterion("company_name is null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNotNull() {
			addCriterion("company_name is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameEqualTo(String value) {
			addCriterion("company_name =", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotEqualTo(String value) {
			addCriterion("company_name <>", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThan(String value) {
			addCriterion("company_name >", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
			addCriterion("company_name >=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThan(String value) {
			addCriterion("company_name <", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThanOrEqualTo(String value) {
			addCriterion("company_name <=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLike(String value) {
			addCriterion("company_name like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotLike(String value) {
			addCriterion("company_name not like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIn(List<String> values) {
			addCriterion("company_name in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotIn(List<String> values) {
			addCriterion("company_name not in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameBetween(String value1, String value2) {
			addCriterion("company_name between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotBetween(String value1, String value2) {
			addCriterion("company_name not between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyRankIsNull() {
			addCriterion("company_rank is null");
			return (Criteria) this;
		}

		public Criteria andCompanyRankIsNotNull() {
			addCriterion("company_rank is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyRankEqualTo(String value) {
			addCriterion("company_rank =", value, "companyRank");
			return (Criteria) this;
		}

		public Criteria andCompanyRankNotEqualTo(String value) {
			addCriterion("company_rank <>", value, "companyRank");
			return (Criteria) this;
		}

		public Criteria andCompanyRankGreaterThan(String value) {
			addCriterion("company_rank >", value, "companyRank");
			return (Criteria) this;
		}

		public Criteria andCompanyRankGreaterThanOrEqualTo(String value) {
			addCriterion("company_rank >=", value, "companyRank");
			return (Criteria) this;
		}

		public Criteria andCompanyRankLessThan(String value) {
			addCriterion("company_rank <", value, "companyRank");
			return (Criteria) this;
		}

		public Criteria andCompanyRankLessThanOrEqualTo(String value) {
			addCriterion("company_rank <=", value, "companyRank");
			return (Criteria) this;
		}

		public Criteria andCompanyRankLike(String value) {
			addCriterion("company_rank like", value, "companyRank");
			return (Criteria) this;
		}

		public Criteria andCompanyRankNotLike(String value) {
			addCriterion("company_rank not like", value, "companyRank");
			return (Criteria) this;
		}

		public Criteria andCompanyRankIn(List<String> values) {
			addCriterion("company_rank in", values, "companyRank");
			return (Criteria) this;
		}

		public Criteria andCompanyRankNotIn(List<String> values) {
			addCriterion("company_rank not in", values, "companyRank");
			return (Criteria) this;
		}

		public Criteria andCompanyRankBetween(String value1, String value2) {
			addCriterion("company_rank between", value1, value2, "companyRank");
			return (Criteria) this;
		}

		public Criteria andCompanyRankNotBetween(String value1, String value2) {
			addCriterion("company_rank not between", value1, value2, "companyRank");
			return (Criteria) this;
		}

		public Criteria andWechatIdIsNull() {
			addCriterion("wechat_id is null");
			return (Criteria) this;
		}

		public Criteria andWechatIdIsNotNull() {
			addCriterion("wechat_id is not null");
			return (Criteria) this;
		}

		public Criteria andWechatIdEqualTo(String value) {
			addCriterion("wechat_id =", value, "wechatId");
			return (Criteria) this;
		}

		public Criteria andWechatIdNotEqualTo(String value) {
			addCriterion("wechat_id <>", value, "wechatId");
			return (Criteria) this;
		}

		public Criteria andWechatIdGreaterThan(String value) {
			addCriterion("wechat_id >", value, "wechatId");
			return (Criteria) this;
		}

		public Criteria andWechatIdGreaterThanOrEqualTo(String value) {
			addCriterion("wechat_id >=", value, "wechatId");
			return (Criteria) this;
		}

		public Criteria andWechatIdLessThan(String value) {
			addCriterion("wechat_id <", value, "wechatId");
			return (Criteria) this;
		}

		public Criteria andWechatIdLessThanOrEqualTo(String value) {
			addCriterion("wechat_id <=", value, "wechatId");
			return (Criteria) this;
		}

		public Criteria andWechatIdLike(String value) {
			addCriterion("wechat_id like", value, "wechatId");
			return (Criteria) this;
		}

		public Criteria andWechatIdNotLike(String value) {
			addCriterion("wechat_id not like", value, "wechatId");
			return (Criteria) this;
		}

		public Criteria andWechatIdIn(List<String> values) {
			addCriterion("wechat_id in", values, "wechatId");
			return (Criteria) this;
		}

		public Criteria andWechatIdNotIn(List<String> values) {
			addCriterion("wechat_id not in", values, "wechatId");
			return (Criteria) this;
		}

		public Criteria andWechatIdBetween(String value1, String value2) {
			addCriterion("wechat_id between", value1, value2, "wechatId");
			return (Criteria) this;
		}

		public Criteria andWechatIdNotBetween(String value1, String value2) {
			addCriterion("wechat_id not between", value1, value2, "wechatId");
			return (Criteria) this;
		}

		public Criteria andStageIdIsNull() {
			addCriterion("stage_id is null");
			return (Criteria) this;
		}

		public Criteria andStageIdIsNotNull() {
			addCriterion("stage_id is not null");
			return (Criteria) this;
		}

		public Criteria andStageIdEqualTo(Integer value) {
			addCriterion("stage_id =", value, "stageId");
			return (Criteria) this;
		}

		public Criteria andStageIdNotEqualTo(Integer value) {
			addCriterion("stage_id <>", value, "stageId");
			return (Criteria) this;
		}

		public Criteria andStageIdGreaterThan(Integer value) {
			addCriterion("stage_id >", value, "stageId");
			return (Criteria) this;
		}

		public Criteria andStageIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("stage_id >=", value, "stageId");
			return (Criteria) this;
		}

		public Criteria andStageIdLessThan(Integer value) {
			addCriterion("stage_id <", value, "stageId");
			return (Criteria) this;
		}

		public Criteria andStageIdLessThanOrEqualTo(Integer value) {
			addCriterion("stage_id <=", value, "stageId");
			return (Criteria) this;
		}

		public Criteria andStageIdIn(List<Integer> values) {
			addCriterion("stage_id in", values, "stageId");
			return (Criteria) this;
		}

		public Criteria andStageIdNotIn(List<Integer> values) {
			addCriterion("stage_id not in", values, "stageId");
			return (Criteria) this;
		}

		public Criteria andStageIdBetween(Integer value1, Integer value2) {
			addCriterion("stage_id between", value1, value2, "stageId");
			return (Criteria) this;
		}

		public Criteria andStageIdNotBetween(Integer value1, Integer value2) {
			addCriterion("stage_id not between", value1, value2, "stageId");
			return (Criteria) this;
		}

		public Criteria andStageNameIsNull() {
			addCriterion("stage_name is null");
			return (Criteria) this;
		}

		public Criteria andStageNameIsNotNull() {
			addCriterion("stage_name is not null");
			return (Criteria) this;
		}

		public Criteria andStageNameEqualTo(String value) {
			addCriterion("stage_name =", value, "stageName");
			return (Criteria) this;
		}

		public Criteria andStageNameNotEqualTo(String value) {
			addCriterion("stage_name <>", value, "stageName");
			return (Criteria) this;
		}

		public Criteria andStageNameGreaterThan(String value) {
			addCriterion("stage_name >", value, "stageName");
			return (Criteria) this;
		}

		public Criteria andStageNameGreaterThanOrEqualTo(String value) {
			addCriterion("stage_name >=", value, "stageName");
			return (Criteria) this;
		}

		public Criteria andStageNameLessThan(String value) {
			addCriterion("stage_name <", value, "stageName");
			return (Criteria) this;
		}

		public Criteria andStageNameLessThanOrEqualTo(String value) {
			addCriterion("stage_name <=", value, "stageName");
			return (Criteria) this;
		}

		public Criteria andStageNameLike(String value) {
			addCriterion("stage_name like", value, "stageName");
			return (Criteria) this;
		}

		public Criteria andStageNameNotLike(String value) {
			addCriterion("stage_name not like", value, "stageName");
			return (Criteria) this;
		}

		public Criteria andStageNameIn(List<String> values) {
			addCriterion("stage_name in", values, "stageName");
			return (Criteria) this;
		}

		public Criteria andStageNameNotIn(List<String> values) {
			addCriterion("stage_name not in", values, "stageName");
			return (Criteria) this;
		}

		public Criteria andStageNameBetween(String value1, String value2) {
			addCriterion("stage_name between", value1, value2, "stageName");
			return (Criteria) this;
		}

		public Criteria andStageNameNotBetween(String value1, String value2) {
			addCriterion("stage_name not between", value1, value2, "stageName");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIdIsNull() {
			addCriterion("single_price_id is null");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIdIsNotNull() {
			addCriterion("single_price_id is not null");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIdEqualTo(Integer value) {
			addCriterion("single_price_id =", value, "singlePriceId");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIdNotEqualTo(Integer value) {
			addCriterion("single_price_id <>", value, "singlePriceId");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIdGreaterThan(Integer value) {
			addCriterion("single_price_id >", value, "singlePriceId");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("single_price_id >=", value, "singlePriceId");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIdLessThan(Integer value) {
			addCriterion("single_price_id <", value, "singlePriceId");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIdLessThanOrEqualTo(Integer value) {
			addCriterion("single_price_id <=", value, "singlePriceId");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIdIn(List<Integer> values) {
			addCriterion("single_price_id in", values, "singlePriceId");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIdNotIn(List<Integer> values) {
			addCriterion("single_price_id not in", values, "singlePriceId");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIdBetween(Integer value1, Integer value2) {
			addCriterion("single_price_id between", value1, value2, "singlePriceId");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("single_price_id not between", value1, value2, "singlePriceId");
			return (Criteria) this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("mobile is null");
			return (Criteria) this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("mobile is not null");
			return (Criteria) this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("mobile =", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("mobile <>", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("mobile >", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("mobile >=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("mobile <", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("mobile <=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("mobile like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("mobile not like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileIn(List<String> values) {
			addCriterion("mobile in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotIn(List<String> values) {
			addCriterion("mobile not in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("mobile between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("mobile not between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andIdCardIsNull() {
			addCriterion("id_card is null");
			return (Criteria) this;
		}

		public Criteria andIdCardIsNotNull() {
			addCriterion("id_card is not null");
			return (Criteria) this;
		}

		public Criteria andIdCardEqualTo(String value) {
			addCriterion("id_card =", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotEqualTo(String value) {
			addCriterion("id_card <>", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardGreaterThan(String value) {
			addCriterion("id_card >", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardGreaterThanOrEqualTo(String value) {
			addCriterion("id_card >=", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardLessThan(String value) {
			addCriterion("id_card <", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardLessThanOrEqualTo(String value) {
			addCriterion("id_card <=", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardLike(String value) {
			addCriterion("id_card like", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotLike(String value) {
			addCriterion("id_card not like", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardIn(List<String> values) {
			addCriterion("id_card in", values, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotIn(List<String> values) {
			addCriterion("id_card not in", values, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardBetween(String value1, String value2) {
			addCriterion("id_card between", value1, value2, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotBetween(String value1, String value2) {
			addCriterion("id_card not between", value1, value2, "idCard");
			return (Criteria) this;
		}

		public Criteria andBusinessCardPositiveIsNull() {
			addCriterion("business_card_positive is null");
			return (Criteria) this;
		}

		public Criteria andBusinessCardPositiveIsNotNull() {
			addCriterion("business_card_positive is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessCardPositiveEqualTo(Integer value) {
			addCriterion("business_card_positive =", value, "businessCardPositive");
			return (Criteria) this;
		}

		public Criteria andBusinessCardPositiveNotEqualTo(Integer value) {
			addCriterion("business_card_positive <>", value, "businessCardPositive");
			return (Criteria) this;
		}

		public Criteria andBusinessCardPositiveGreaterThan(Integer value) {
			addCriterion("business_card_positive >", value, "businessCardPositive");
			return (Criteria) this;
		}

		public Criteria andBusinessCardPositiveGreaterThanOrEqualTo(Integer value) {
			addCriterion("business_card_positive >=", value, "businessCardPositive");
			return (Criteria) this;
		}

		public Criteria andBusinessCardPositiveLessThan(Integer value) {
			addCriterion("business_card_positive <", value, "businessCardPositive");
			return (Criteria) this;
		}

		public Criteria andBusinessCardPositiveLessThanOrEqualTo(Integer value) {
			addCriterion("business_card_positive <=", value, "businessCardPositive");
			return (Criteria) this;
		}

		public Criteria andBusinessCardPositiveIn(List<Integer> values) {
			addCriterion("business_card_positive in", values, "businessCardPositive");
			return (Criteria) this;
		}

		public Criteria andBusinessCardPositiveNotIn(List<Integer> values) {
			addCriterion("business_card_positive not in", values, "businessCardPositive");
			return (Criteria) this;
		}

		public Criteria andBusinessCardPositiveBetween(Integer value1, Integer value2) {
			addCriterion("business_card_positive between", value1, value2, "businessCardPositive");
			return (Criteria) this;
		}

		public Criteria andBusinessCardPositiveNotBetween(Integer value1, Integer value2) {
			addCriterion("business_card_positive not between", value1, value2, "businessCardPositive");
			return (Criteria) this;
		}

		public Criteria andBusinessCardOppositeIsNull() {
			addCriterion("business_card_opposite is null");
			return (Criteria) this;
		}

		public Criteria andBusinessCardOppositeIsNotNull() {
			addCriterion("business_card_opposite is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessCardOppositeEqualTo(Integer value) {
			addCriterion("business_card_opposite =", value, "businessCardOpposite");
			return (Criteria) this;
		}

		public Criteria andBusinessCardOppositeNotEqualTo(Integer value) {
			addCriterion("business_card_opposite <>", value, "businessCardOpposite");
			return (Criteria) this;
		}

		public Criteria andBusinessCardOppositeGreaterThan(Integer value) {
			addCriterion("business_card_opposite >", value, "businessCardOpposite");
			return (Criteria) this;
		}

		public Criteria andBusinessCardOppositeGreaterThanOrEqualTo(Integer value) {
			addCriterion("business_card_opposite >=", value, "businessCardOpposite");
			return (Criteria) this;
		}

		public Criteria andBusinessCardOppositeLessThan(Integer value) {
			addCriterion("business_card_opposite <", value, "businessCardOpposite");
			return (Criteria) this;
		}

		public Criteria andBusinessCardOppositeLessThanOrEqualTo(Integer value) {
			addCriterion("business_card_opposite <=", value, "businessCardOpposite");
			return (Criteria) this;
		}

		public Criteria andBusinessCardOppositeIn(List<Integer> values) {
			addCriterion("business_card_opposite in", values, "businessCardOpposite");
			return (Criteria) this;
		}

		public Criteria andBusinessCardOppositeNotIn(List<Integer> values) {
			addCriterion("business_card_opposite not in", values, "businessCardOpposite");
			return (Criteria) this;
		}

		public Criteria andBusinessCardOppositeBetween(Integer value1, Integer value2) {
			addCriterion("business_card_opposite between", value1, value2, "businessCardOpposite");
			return (Criteria) this;
		}

		public Criteria andBusinessCardOppositeNotBetween(Integer value1, Integer value2) {
			addCriterion("business_card_opposite not between", value1, value2, "businessCardOpposite");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIdIsNull() {
			addCriterion("personal_assets_id is null");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIdIsNotNull() {
			addCriterion("personal_assets_id is not null");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIdEqualTo(Integer value) {
			addCriterion("personal_assets_id =", value, "personalAssetsId");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIdNotEqualTo(Integer value) {
			addCriterion("personal_assets_id <>", value, "personalAssetsId");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIdGreaterThan(Integer value) {
			addCriterion("personal_assets_id >", value, "personalAssetsId");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("personal_assets_id >=", value, "personalAssetsId");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIdLessThan(Integer value) {
			addCriterion("personal_assets_id <", value, "personalAssetsId");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIdLessThanOrEqualTo(Integer value) {
			addCriterion("personal_assets_id <=", value, "personalAssetsId");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIdIn(List<Integer> values) {
			addCriterion("personal_assets_id in", values, "personalAssetsId");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIdNotIn(List<Integer> values) {
			addCriterion("personal_assets_id not in", values, "personalAssetsId");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIdBetween(Integer value1, Integer value2) {
			addCriterion("personal_assets_id between", value1, value2, "personalAssetsId");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIdNotBetween(Integer value1, Integer value2) {
			addCriterion("personal_assets_id not between", value1, value2, "personalAssetsId");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIsNull() {
			addCriterion("personal_assets is null");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIsNotNull() {
			addCriterion("personal_assets is not null");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsEqualTo(String value) {
			addCriterion("personal_assets =", value, "personalAssets");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsNotEqualTo(String value) {
			addCriterion("personal_assets <>", value, "personalAssets");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsGreaterThan(String value) {
			addCriterion("personal_assets >", value, "personalAssets");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsGreaterThanOrEqualTo(String value) {
			addCriterion("personal_assets >=", value, "personalAssets");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsLessThan(String value) {
			addCriterion("personal_assets <", value, "personalAssets");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsLessThanOrEqualTo(String value) {
			addCriterion("personal_assets <=", value, "personalAssets");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsLike(String value) {
			addCriterion("personal_assets like", value, "personalAssets");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsNotLike(String value) {
			addCriterion("personal_assets not like", value, "personalAssets");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsIn(List<String> values) {
			addCriterion("personal_assets in", values, "personalAssets");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsNotIn(List<String> values) {
			addCriterion("personal_assets not in", values, "personalAssets");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsBetween(String value1, String value2) {
			addCriterion("personal_assets between", value1, value2, "personalAssets");
			return (Criteria) this;
		}

		public Criteria andPersonalAssetsNotBetween(String value1, String value2) {
			addCriterion("personal_assets not between", value1, value2, "personalAssets");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_investor
	 * @mbggenerated  Sun Mar 05 18:53:24 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_investor
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 05 12:42:20 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}