package com.qheeshow.eway.service.model;

public class InvestorWithBLOBs extends Investor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.city_id
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	private String cityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.city_name
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	private String cityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.stage_id
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	private String stageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.stage_name
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	private String stageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.field_id
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	private String fieldId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.field_name
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	private String fieldName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.single_price
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	private String singlePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.style
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	private String style;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.preference_id
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	private String preferenceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.preference
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	private String preference;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.investor_case
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	private String investorCase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.recommender
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	private String recommender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_investor.personal_profile
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	private String personalProfile;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.city_id
	 * @return  the value of t_investor.city_id
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public String getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.city_id
	 * @param cityId  the value for t_investor.city_id
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.city_name
	 * @return  the value of t_investor.city_name
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.city_name
	 * @param cityName  the value for t_investor.city_name
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.stage_id
	 * @return  the value of t_investor.stage_id
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public String getStageId() {
		return stageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.stage_id
	 * @param stageId  the value for t_investor.stage_id
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public void setStageId(String stageId) {
		this.stageId = stageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.stage_name
	 * @return  the value of t_investor.stage_name
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public String getStageName() {
		return stageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.stage_name
	 * @param stageName  the value for t_investor.stage_name
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public void setStageName(String stageName) {
		this.stageName = stageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.field_id
	 * @return  the value of t_investor.field_id
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public String getFieldId() {
		return fieldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.field_id
	 * @param fieldId  the value for t_investor.field_id
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public void setFieldId(String fieldId) {
		this.fieldId = fieldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.field_name
	 * @return  the value of t_investor.field_name
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public String getFieldName() {
		return fieldName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.field_name
	 * @param fieldName  the value for t_investor.field_name
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.single_price
	 * @return  the value of t_investor.single_price
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public String getSinglePrice() {
		return singlePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.single_price
	 * @param singlePrice  the value for t_investor.single_price
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public void setSinglePrice(String singlePrice) {
		this.singlePrice = singlePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.style
	 * @return  the value of t_investor.style
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public String getStyle() {
		return style;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.style
	 * @param style  the value for t_investor.style
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public void setStyle(String style) {
		this.style = style;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.preference_id
	 * @return  the value of t_investor.preference_id
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public String getPreferenceId() {
		return preferenceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.preference_id
	 * @param preferenceId  the value for t_investor.preference_id
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public void setPreferenceId(String preferenceId) {
		this.preferenceId = preferenceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.preference
	 * @return  the value of t_investor.preference
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public String getPreference() {
		return preference;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.preference
	 * @param preference  the value for t_investor.preference
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public void setPreference(String preference) {
		this.preference = preference;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.investor_case
	 * @return  the value of t_investor.investor_case
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public String getInvestorCase() {
		return investorCase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.investor_case
	 * @param investorCase  the value for t_investor.investor_case
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public void setInvestorCase(String investorCase) {
		this.investorCase = investorCase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.recommender
	 * @return  the value of t_investor.recommender
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public String getRecommender() {
		return recommender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.recommender
	 * @param recommender  the value for t_investor.recommender
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public void setRecommender(String recommender) {
		this.recommender = recommender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_investor.personal_profile
	 * @return  the value of t_investor.personal_profile
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public String getPersonalProfile() {
		return personalProfile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_investor.personal_profile
	 * @param personalProfile  the value for t_investor.personal_profile
	 * @mbggenerated  Sun Mar 05 19:26:48 CST 2017
	 */
	public void setPersonalProfile(String personalProfile) {
		this.personalProfile = personalProfile;
	}

}