package com.qheeshow.eway.service.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUseridIsNull() {
			addCriterion("USERID is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("USERID is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(Integer value) {
			addCriterion("USERID =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(Integer value) {
			addCriterion("USERID <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(Integer value) {
			addCriterion("USERID >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("USERID >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(Integer value) {
			addCriterion("USERID <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(Integer value) {
			addCriterion("USERID <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<Integer> values) {
			addCriterion("USERID in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<Integer> values) {
			addCriterion("USERID not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(Integer value1, Integer value2) {
			addCriterion("USERID between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(Integer value1, Integer value2) {
			addCriterion("USERID not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("USERNAME is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("USERNAME is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("USERNAME =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("USERNAME <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("USERNAME >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("USERNAME >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("USERNAME <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("USERNAME <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("USERNAME like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("USERNAME not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("USERNAME in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("USERNAME not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("USERNAME between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("USERNAME not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("PASSWORD in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("PASSWORD not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNull() {
			addCriterion("NICKNAME is null");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNotNull() {
			addCriterion("NICKNAME is not null");
			return (Criteria) this;
		}

		public Criteria andNicknameEqualTo(String value) {
			addCriterion("NICKNAME =", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotEqualTo(String value) {
			addCriterion("NICKNAME <>", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThan(String value) {
			addCriterion("NICKNAME >", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThanOrEqualTo(String value) {
			addCriterion("NICKNAME >=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThan(String value) {
			addCriterion("NICKNAME <", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThanOrEqualTo(String value) {
			addCriterion("NICKNAME <=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLike(String value) {
			addCriterion("NICKNAME like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotLike(String value) {
			addCriterion("NICKNAME not like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameIn(List<String> values) {
			addCriterion("NICKNAME in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotIn(List<String> values) {
			addCriterion("NICKNAME not in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameBetween(String value1, String value2) {
			addCriterion("NICKNAME between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotBetween(String value1, String value2) {
			addCriterion("NICKNAME not between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andTruenameIsNull() {
			addCriterion("TRUENAME is null");
			return (Criteria) this;
		}

		public Criteria andTruenameIsNotNull() {
			addCriterion("TRUENAME is not null");
			return (Criteria) this;
		}

		public Criteria andTruenameEqualTo(String value) {
			addCriterion("TRUENAME =", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameNotEqualTo(String value) {
			addCriterion("TRUENAME <>", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameGreaterThan(String value) {
			addCriterion("TRUENAME >", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameGreaterThanOrEqualTo(String value) {
			addCriterion("TRUENAME >=", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameLessThan(String value) {
			addCriterion("TRUENAME <", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameLessThanOrEqualTo(String value) {
			addCriterion("TRUENAME <=", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameLike(String value) {
			addCriterion("TRUENAME like", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameNotLike(String value) {
			addCriterion("TRUENAME not like", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameIn(List<String> values) {
			addCriterion("TRUENAME in", values, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameNotIn(List<String> values) {
			addCriterion("TRUENAME not in", values, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameBetween(String value1, String value2) {
			addCriterion("TRUENAME between", value1, value2, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameNotBetween(String value1, String value2) {
			addCriterion("TRUENAME not between", value1, value2, "truename");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("ADDRESS is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("ADDRESS is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("ADDRESS =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("ADDRESS <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("ADDRESS >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("ADDRESS >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("ADDRESS <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("ADDRESS <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("ADDRESS like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("ADDRESS not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("ADDRESS in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("ADDRESS not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("ADDRESS between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("ADDRESS not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andTelIsNull() {
			addCriterion("TEL is null");
			return (Criteria) this;
		}

		public Criteria andTelIsNotNull() {
			addCriterion("TEL is not null");
			return (Criteria) this;
		}

		public Criteria andTelEqualTo(String value) {
			addCriterion("TEL =", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotEqualTo(String value) {
			addCriterion("TEL <>", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThan(String value) {
			addCriterion("TEL >", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThanOrEqualTo(String value) {
			addCriterion("TEL >=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThan(String value) {
			addCriterion("TEL <", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThanOrEqualTo(String value) {
			addCriterion("TEL <=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLike(String value) {
			addCriterion("TEL like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotLike(String value) {
			addCriterion("TEL not like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelIn(List<String> values) {
			addCriterion("TEL in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotIn(List<String> values) {
			addCriterion("TEL not in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelBetween(String value1, String value2) {
			addCriterion("TEL between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotBetween(String value1, String value2) {
			addCriterion("TEL not between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("MOBILE is null");
			return (Criteria) this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("MOBILE is not null");
			return (Criteria) this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("MOBILE =", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("MOBILE <>", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("MOBILE >", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("MOBILE >=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("MOBILE <", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("MOBILE <=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("MOBILE like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("MOBILE not like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileIn(List<String> values) {
			addCriterion("MOBILE in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotIn(List<String> values) {
			addCriterion("MOBILE not in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("MOBILE between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("MOBILE not between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("EMAIL is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("EMAIL is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("EMAIL =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("EMAIL <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("EMAIL >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("EMAIL <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("EMAIL <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("EMAIL like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("EMAIL not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("EMAIL in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("EMAIL not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("EMAIL between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("EMAIL not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andReminderquestionIsNull() {
			addCriterion("REMINDERQUESTION is null");
			return (Criteria) this;
		}

		public Criteria andReminderquestionIsNotNull() {
			addCriterion("REMINDERQUESTION is not null");
			return (Criteria) this;
		}

		public Criteria andReminderquestionEqualTo(String value) {
			addCriterion("REMINDERQUESTION =", value, "reminderquestion");
			return (Criteria) this;
		}

		public Criteria andReminderquestionNotEqualTo(String value) {
			addCriterion("REMINDERQUESTION <>", value, "reminderquestion");
			return (Criteria) this;
		}

		public Criteria andReminderquestionGreaterThan(String value) {
			addCriterion("REMINDERQUESTION >", value, "reminderquestion");
			return (Criteria) this;
		}

		public Criteria andReminderquestionGreaterThanOrEqualTo(String value) {
			addCriterion("REMINDERQUESTION >=", value, "reminderquestion");
			return (Criteria) this;
		}

		public Criteria andReminderquestionLessThan(String value) {
			addCriterion("REMINDERQUESTION <", value, "reminderquestion");
			return (Criteria) this;
		}

		public Criteria andReminderquestionLessThanOrEqualTo(String value) {
			addCriterion("REMINDERQUESTION <=", value, "reminderquestion");
			return (Criteria) this;
		}

		public Criteria andReminderquestionLike(String value) {
			addCriterion("REMINDERQUESTION like", value, "reminderquestion");
			return (Criteria) this;
		}

		public Criteria andReminderquestionNotLike(String value) {
			addCriterion("REMINDERQUESTION not like", value, "reminderquestion");
			return (Criteria) this;
		}

		public Criteria andReminderquestionIn(List<String> values) {
			addCriterion("REMINDERQUESTION in", values, "reminderquestion");
			return (Criteria) this;
		}

		public Criteria andReminderquestionNotIn(List<String> values) {
			addCriterion("REMINDERQUESTION not in", values, "reminderquestion");
			return (Criteria) this;
		}

		public Criteria andReminderquestionBetween(String value1, String value2) {
			addCriterion("REMINDERQUESTION between", value1, value2, "reminderquestion");
			return (Criteria) this;
		}

		public Criteria andReminderquestionNotBetween(String value1, String value2) {
			addCriterion("REMINDERQUESTION not between", value1, value2, "reminderquestion");
			return (Criteria) this;
		}

		public Criteria andReminderanswerIsNull() {
			addCriterion("REMINDERANSWER is null");
			return (Criteria) this;
		}

		public Criteria andReminderanswerIsNotNull() {
			addCriterion("REMINDERANSWER is not null");
			return (Criteria) this;
		}

		public Criteria andReminderanswerEqualTo(String value) {
			addCriterion("REMINDERANSWER =", value, "reminderanswer");
			return (Criteria) this;
		}

		public Criteria andReminderanswerNotEqualTo(String value) {
			addCriterion("REMINDERANSWER <>", value, "reminderanswer");
			return (Criteria) this;
		}

		public Criteria andReminderanswerGreaterThan(String value) {
			addCriterion("REMINDERANSWER >", value, "reminderanswer");
			return (Criteria) this;
		}

		public Criteria andReminderanswerGreaterThanOrEqualTo(String value) {
			addCriterion("REMINDERANSWER >=", value, "reminderanswer");
			return (Criteria) this;
		}

		public Criteria andReminderanswerLessThan(String value) {
			addCriterion("REMINDERANSWER <", value, "reminderanswer");
			return (Criteria) this;
		}

		public Criteria andReminderanswerLessThanOrEqualTo(String value) {
			addCriterion("REMINDERANSWER <=", value, "reminderanswer");
			return (Criteria) this;
		}

		public Criteria andReminderanswerLike(String value) {
			addCriterion("REMINDERANSWER like", value, "reminderanswer");
			return (Criteria) this;
		}

		public Criteria andReminderanswerNotLike(String value) {
			addCriterion("REMINDERANSWER not like", value, "reminderanswer");
			return (Criteria) this;
		}

		public Criteria andReminderanswerIn(List<String> values) {
			addCriterion("REMINDERANSWER in", values, "reminderanswer");
			return (Criteria) this;
		}

		public Criteria andReminderanswerNotIn(List<String> values) {
			addCriterion("REMINDERANSWER not in", values, "reminderanswer");
			return (Criteria) this;
		}

		public Criteria andReminderanswerBetween(String value1, String value2) {
			addCriterion("REMINDERANSWER between", value1, value2, "reminderanswer");
			return (Criteria) this;
		}

		public Criteria andReminderanswerNotBetween(String value1, String value2) {
			addCriterion("REMINDERANSWER not between", value1, value2, "reminderanswer");
			return (Criteria) this;
		}

		public Criteria andIfpubmyinfoIsNull() {
			addCriterion("IFPUBMYINFO is null");
			return (Criteria) this;
		}

		public Criteria andIfpubmyinfoIsNotNull() {
			addCriterion("IFPUBMYINFO is not null");
			return (Criteria) this;
		}

		public Criteria andIfpubmyinfoEqualTo(Byte value) {
			addCriterion("IFPUBMYINFO =", value, "ifpubmyinfo");
			return (Criteria) this;
		}

		public Criteria andIfpubmyinfoNotEqualTo(Byte value) {
			addCriterion("IFPUBMYINFO <>", value, "ifpubmyinfo");
			return (Criteria) this;
		}

		public Criteria andIfpubmyinfoGreaterThan(Byte value) {
			addCriterion("IFPUBMYINFO >", value, "ifpubmyinfo");
			return (Criteria) this;
		}

		public Criteria andIfpubmyinfoGreaterThanOrEqualTo(Byte value) {
			addCriterion("IFPUBMYINFO >=", value, "ifpubmyinfo");
			return (Criteria) this;
		}

		public Criteria andIfpubmyinfoLessThan(Byte value) {
			addCriterion("IFPUBMYINFO <", value, "ifpubmyinfo");
			return (Criteria) this;
		}

		public Criteria andIfpubmyinfoLessThanOrEqualTo(Byte value) {
			addCriterion("IFPUBMYINFO <=", value, "ifpubmyinfo");
			return (Criteria) this;
		}

		public Criteria andIfpubmyinfoIn(List<Byte> values) {
			addCriterion("IFPUBMYINFO in", values, "ifpubmyinfo");
			return (Criteria) this;
		}

		public Criteria andIfpubmyinfoNotIn(List<Byte> values) {
			addCriterion("IFPUBMYINFO not in", values, "ifpubmyinfo");
			return (Criteria) this;
		}

		public Criteria andIfpubmyinfoBetween(Byte value1, Byte value2) {
			addCriterion("IFPUBMYINFO between", value1, value2, "ifpubmyinfo");
			return (Criteria) this;
		}

		public Criteria andIfpubmyinfoNotBetween(Byte value1, Byte value2) {
			addCriterion("IFPUBMYINFO not between", value1, value2, "ifpubmyinfo");
			return (Criteria) this;
		}

		public Criteria andApplytimeIsNull() {
			addCriterion("APPLYTIME is null");
			return (Criteria) this;
		}

		public Criteria andApplytimeIsNotNull() {
			addCriterion("APPLYTIME is not null");
			return (Criteria) this;
		}

		public Criteria andApplytimeEqualTo(Date value) {
			addCriterion("APPLYTIME =", value, "applytime");
			return (Criteria) this;
		}

		public Criteria andApplytimeNotEqualTo(Date value) {
			addCriterion("APPLYTIME <>", value, "applytime");
			return (Criteria) this;
		}

		public Criteria andApplytimeGreaterThan(Date value) {
			addCriterion("APPLYTIME >", value, "applytime");
			return (Criteria) this;
		}

		public Criteria andApplytimeGreaterThanOrEqualTo(Date value) {
			addCriterion("APPLYTIME >=", value, "applytime");
			return (Criteria) this;
		}

		public Criteria andApplytimeLessThan(Date value) {
			addCriterion("APPLYTIME <", value, "applytime");
			return (Criteria) this;
		}

		public Criteria andApplytimeLessThanOrEqualTo(Date value) {
			addCriterion("APPLYTIME <=", value, "applytime");
			return (Criteria) this;
		}

		public Criteria andApplytimeIn(List<Date> values) {
			addCriterion("APPLYTIME in", values, "applytime");
			return (Criteria) this;
		}

		public Criteria andApplytimeNotIn(List<Date> values) {
			addCriterion("APPLYTIME not in", values, "applytime");
			return (Criteria) this;
		}

		public Criteria andApplytimeBetween(Date value1, Date value2) {
			addCriterion("APPLYTIME between", value1, value2, "applytime");
			return (Criteria) this;
		}

		public Criteria andApplytimeNotBetween(Date value1, Date value2) {
			addCriterion("APPLYTIME not between", value1, value2, "applytime");
			return (Criteria) this;
		}

		public Criteria andRegtimeIsNull() {
			addCriterion("REGTIME is null");
			return (Criteria) this;
		}

		public Criteria andRegtimeIsNotNull() {
			addCriterion("REGTIME is not null");
			return (Criteria) this;
		}

		public Criteria andRegtimeEqualTo(Date value) {
			addCriterion("REGTIME =", value, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeNotEqualTo(Date value) {
			addCriterion("REGTIME <>", value, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeGreaterThan(Date value) {
			addCriterion("REGTIME >", value, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("REGTIME >=", value, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeLessThan(Date value) {
			addCriterion("REGTIME <", value, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeLessThanOrEqualTo(Date value) {
			addCriterion("REGTIME <=", value, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeIn(List<Date> values) {
			addCriterion("REGTIME in", values, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeNotIn(List<Date> values) {
			addCriterion("REGTIME not in", values, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeBetween(Date value1, Date value2) {
			addCriterion("REGTIME between", value1, value2, "regtime");
			return (Criteria) this;
		}

		public Criteria andRegtimeNotBetween(Date value1, Date value2) {
			addCriterion("REGTIME not between", value1, value2, "regtime");
			return (Criteria) this;
		}

		public Criteria andLogintimesIsNull() {
			addCriterion("LOGINTIMES is null");
			return (Criteria) this;
		}

		public Criteria andLogintimesIsNotNull() {
			addCriterion("LOGINTIMES is not null");
			return (Criteria) this;
		}

		public Criteria andLogintimesEqualTo(Integer value) {
			addCriterion("LOGINTIMES =", value, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesNotEqualTo(Integer value) {
			addCriterion("LOGINTIMES <>", value, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesGreaterThan(Integer value) {
			addCriterion("LOGINTIMES >", value, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesGreaterThanOrEqualTo(Integer value) {
			addCriterion("LOGINTIMES >=", value, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesLessThan(Integer value) {
			addCriterion("LOGINTIMES <", value, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesLessThanOrEqualTo(Integer value) {
			addCriterion("LOGINTIMES <=", value, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesIn(List<Integer> values) {
			addCriterion("LOGINTIMES in", values, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesNotIn(List<Integer> values) {
			addCriterion("LOGINTIMES not in", values, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesBetween(Integer value1, Integer value2) {
			addCriterion("LOGINTIMES between", value1, value2, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimesNotBetween(Integer value1, Integer value2) {
			addCriterion("LOGINTIMES not between", value1, value2, "logintimes");
			return (Criteria) this;
		}

		public Criteria andLogintimeIsNull() {
			addCriterion("LOGINTIME is null");
			return (Criteria) this;
		}

		public Criteria andLogintimeIsNotNull() {
			addCriterion("LOGINTIME is not null");
			return (Criteria) this;
		}

		public Criteria andLogintimeEqualTo(Date value) {
			addCriterion("LOGINTIME =", value, "logintime");
			return (Criteria) this;
		}

		public Criteria andLogintimeNotEqualTo(Date value) {
			addCriterion("LOGINTIME <>", value, "logintime");
			return (Criteria) this;
		}

		public Criteria andLogintimeGreaterThan(Date value) {
			addCriterion("LOGINTIME >", value, "logintime");
			return (Criteria) this;
		}

		public Criteria andLogintimeGreaterThanOrEqualTo(Date value) {
			addCriterion("LOGINTIME >=", value, "logintime");
			return (Criteria) this;
		}

		public Criteria andLogintimeLessThan(Date value) {
			addCriterion("LOGINTIME <", value, "logintime");
			return (Criteria) this;
		}

		public Criteria andLogintimeLessThanOrEqualTo(Date value) {
			addCriterion("LOGINTIME <=", value, "logintime");
			return (Criteria) this;
		}

		public Criteria andLogintimeIn(List<Date> values) {
			addCriterion("LOGINTIME in", values, "logintime");
			return (Criteria) this;
		}

		public Criteria andLogintimeNotIn(List<Date> values) {
			addCriterion("LOGINTIME not in", values, "logintime");
			return (Criteria) this;
		}

		public Criteria andLogintimeBetween(Date value1, Date value2) {
			addCriterion("LOGINTIME between", value1, value2, "logintime");
			return (Criteria) this;
		}

		public Criteria andLogintimeNotBetween(Date value1, Date value2) {
			addCriterion("LOGINTIME not between", value1, value2, "logintime");
			return (Criteria) this;
		}

		public Criteria andLogouttimeIsNull() {
			addCriterion("LOGOUTTIME is null");
			return (Criteria) this;
		}

		public Criteria andLogouttimeIsNotNull() {
			addCriterion("LOGOUTTIME is not null");
			return (Criteria) this;
		}

		public Criteria andLogouttimeEqualTo(Date value) {
			addCriterion("LOGOUTTIME =", value, "logouttime");
			return (Criteria) this;
		}

		public Criteria andLogouttimeNotEqualTo(Date value) {
			addCriterion("LOGOUTTIME <>", value, "logouttime");
			return (Criteria) this;
		}

		public Criteria andLogouttimeGreaterThan(Date value) {
			addCriterion("LOGOUTTIME >", value, "logouttime");
			return (Criteria) this;
		}

		public Criteria andLogouttimeGreaterThanOrEqualTo(Date value) {
			addCriterion("LOGOUTTIME >=", value, "logouttime");
			return (Criteria) this;
		}

		public Criteria andLogouttimeLessThan(Date value) {
			addCriterion("LOGOUTTIME <", value, "logouttime");
			return (Criteria) this;
		}

		public Criteria andLogouttimeLessThanOrEqualTo(Date value) {
			addCriterion("LOGOUTTIME <=", value, "logouttime");
			return (Criteria) this;
		}

		public Criteria andLogouttimeIn(List<Date> values) {
			addCriterion("LOGOUTTIME in", values, "logouttime");
			return (Criteria) this;
		}

		public Criteria andLogouttimeNotIn(List<Date> values) {
			addCriterion("LOGOUTTIME not in", values, "logouttime");
			return (Criteria) this;
		}

		public Criteria andLogouttimeBetween(Date value1, Date value2) {
			addCriterion("LOGOUTTIME between", value1, value2, "logouttime");
			return (Criteria) this;
		}

		public Criteria andLogouttimeNotBetween(Date value1, Date value2) {
			addCriterion("LOGOUTTIME not between", value1, value2, "logouttime");
			return (Criteria) this;
		}

		public Criteria andMsgintervalIsNull() {
			addCriterion("MSGINTERVAL is null");
			return (Criteria) this;
		}

		public Criteria andMsgintervalIsNotNull() {
			addCriterion("MSGINTERVAL is not null");
			return (Criteria) this;
		}

		public Criteria andMsgintervalEqualTo(Short value) {
			addCriterion("MSGINTERVAL =", value, "msginterval");
			return (Criteria) this;
		}

		public Criteria andMsgintervalNotEqualTo(Short value) {
			addCriterion("MSGINTERVAL <>", value, "msginterval");
			return (Criteria) this;
		}

		public Criteria andMsgintervalGreaterThan(Short value) {
			addCriterion("MSGINTERVAL >", value, "msginterval");
			return (Criteria) this;
		}

		public Criteria andMsgintervalGreaterThanOrEqualTo(Short value) {
			addCriterion("MSGINTERVAL >=", value, "msginterval");
			return (Criteria) this;
		}

		public Criteria andMsgintervalLessThan(Short value) {
			addCriterion("MSGINTERVAL <", value, "msginterval");
			return (Criteria) this;
		}

		public Criteria andMsgintervalLessThanOrEqualTo(Short value) {
			addCriterion("MSGINTERVAL <=", value, "msginterval");
			return (Criteria) this;
		}

		public Criteria andMsgintervalIn(List<Short> values) {
			addCriterion("MSGINTERVAL in", values, "msginterval");
			return (Criteria) this;
		}

		public Criteria andMsgintervalNotIn(List<Short> values) {
			addCriterion("MSGINTERVAL not in", values, "msginterval");
			return (Criteria) this;
		}

		public Criteria andMsgintervalBetween(Short value1, Short value2) {
			addCriterion("MSGINTERVAL between", value1, value2, "msginterval");
			return (Criteria) this;
		}

		public Criteria andMsgintervalNotBetween(Short value1, Short value2) {
			addCriterion("MSGINTERVAL not between", value1, value2, "msginterval");
			return (Criteria) this;
		}

		public Criteria andViewintervalIsNull() {
			addCriterion("VIEWINTERVAL is null");
			return (Criteria) this;
		}

		public Criteria andViewintervalIsNotNull() {
			addCriterion("VIEWINTERVAL is not null");
			return (Criteria) this;
		}

		public Criteria andViewintervalEqualTo(Short value) {
			addCriterion("VIEWINTERVAL =", value, "viewinterval");
			return (Criteria) this;
		}

		public Criteria andViewintervalNotEqualTo(Short value) {
			addCriterion("VIEWINTERVAL <>", value, "viewinterval");
			return (Criteria) this;
		}

		public Criteria andViewintervalGreaterThan(Short value) {
			addCriterion("VIEWINTERVAL >", value, "viewinterval");
			return (Criteria) this;
		}

		public Criteria andViewintervalGreaterThanOrEqualTo(Short value) {
			addCriterion("VIEWINTERVAL >=", value, "viewinterval");
			return (Criteria) this;
		}

		public Criteria andViewintervalLessThan(Short value) {
			addCriterion("VIEWINTERVAL <", value, "viewinterval");
			return (Criteria) this;
		}

		public Criteria andViewintervalLessThanOrEqualTo(Short value) {
			addCriterion("VIEWINTERVAL <=", value, "viewinterval");
			return (Criteria) this;
		}

		public Criteria andViewintervalIn(List<Short> values) {
			addCriterion("VIEWINTERVAL in", values, "viewinterval");
			return (Criteria) this;
		}

		public Criteria andViewintervalNotIn(List<Short> values) {
			addCriterion("VIEWINTERVAL not in", values, "viewinterval");
			return (Criteria) this;
		}

		public Criteria andViewintervalBetween(Short value1, Short value2) {
			addCriterion("VIEWINTERVAL between", value1, value2, "viewinterval");
			return (Criteria) this;
		}

		public Criteria andViewintervalNotBetween(Short value1, Short value2) {
			addCriterion("VIEWINTERVAL not between", value1, value2, "viewinterval");
			return (Criteria) this;
		}

		public Criteria andAttributeIsNull() {
			addCriterion("ATTRIBUTE is null");
			return (Criteria) this;
		}

		public Criteria andAttributeIsNotNull() {
			addCriterion("ATTRIBUTE is not null");
			return (Criteria) this;
		}

		public Criteria andAttributeEqualTo(String value) {
			addCriterion("ATTRIBUTE =", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeNotEqualTo(String value) {
			addCriterion("ATTRIBUTE <>", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeGreaterThan(String value) {
			addCriterion("ATTRIBUTE >", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeGreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE >=", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeLessThan(String value) {
			addCriterion("ATTRIBUTE <", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeLessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE <=", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeLike(String value) {
			addCriterion("ATTRIBUTE like", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeNotLike(String value) {
			addCriterion("ATTRIBUTE not like", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeIn(List<String> values) {
			addCriterion("ATTRIBUTE in", values, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeNotIn(List<String> values) {
			addCriterion("ATTRIBUTE not in", values, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE between", value1, value2, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeNotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE not between", value1, value2, "attribute");
			return (Criteria) this;
		}

		public Criteria andCruserIsNull() {
			addCriterion("CRUSER is null");
			return (Criteria) this;
		}

		public Criteria andCruserIsNotNull() {
			addCriterion("CRUSER is not null");
			return (Criteria) this;
		}

		public Criteria andCruserEqualTo(String value) {
			addCriterion("CRUSER =", value, "cruser");
			return (Criteria) this;
		}

		public Criteria andCruserNotEqualTo(String value) {
			addCriterion("CRUSER <>", value, "cruser");
			return (Criteria) this;
		}

		public Criteria andCruserGreaterThan(String value) {
			addCriterion("CRUSER >", value, "cruser");
			return (Criteria) this;
		}

		public Criteria andCruserGreaterThanOrEqualTo(String value) {
			addCriterion("CRUSER >=", value, "cruser");
			return (Criteria) this;
		}

		public Criteria andCruserLessThan(String value) {
			addCriterion("CRUSER <", value, "cruser");
			return (Criteria) this;
		}

		public Criteria andCruserLessThanOrEqualTo(String value) {
			addCriterion("CRUSER <=", value, "cruser");
			return (Criteria) this;
		}

		public Criteria andCruserLike(String value) {
			addCriterion("CRUSER like", value, "cruser");
			return (Criteria) this;
		}

		public Criteria andCruserNotLike(String value) {
			addCriterion("CRUSER not like", value, "cruser");
			return (Criteria) this;
		}

		public Criteria andCruserIn(List<String> values) {
			addCriterion("CRUSER in", values, "cruser");
			return (Criteria) this;
		}

		public Criteria andCruserNotIn(List<String> values) {
			addCriterion("CRUSER not in", values, "cruser");
			return (Criteria) this;
		}

		public Criteria andCruserBetween(String value1, String value2) {
			addCriterion("CRUSER between", value1, value2, "cruser");
			return (Criteria) this;
		}

		public Criteria andCruserNotBetween(String value1, String value2) {
			addCriterion("CRUSER not between", value1, value2, "cruser");
			return (Criteria) this;
		}

		public Criteria andCrtimeIsNull() {
			addCriterion("CRTIME is null");
			return (Criteria) this;
		}

		public Criteria andCrtimeIsNotNull() {
			addCriterion("CRTIME is not null");
			return (Criteria) this;
		}

		public Criteria andCrtimeEqualTo(Date value) {
			addCriterion("CRTIME =", value, "crtime");
			return (Criteria) this;
		}

		public Criteria andCrtimeNotEqualTo(Date value) {
			addCriterion("CRTIME <>", value, "crtime");
			return (Criteria) this;
		}

		public Criteria andCrtimeGreaterThan(Date value) {
			addCriterion("CRTIME >", value, "crtime");
			return (Criteria) this;
		}

		public Criteria andCrtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CRTIME >=", value, "crtime");
			return (Criteria) this;
		}

		public Criteria andCrtimeLessThan(Date value) {
			addCriterion("CRTIME <", value, "crtime");
			return (Criteria) this;
		}

		public Criteria andCrtimeLessThanOrEqualTo(Date value) {
			addCriterion("CRTIME <=", value, "crtime");
			return (Criteria) this;
		}

		public Criteria andCrtimeIn(List<Date> values) {
			addCriterion("CRTIME in", values, "crtime");
			return (Criteria) this;
		}

		public Criteria andCrtimeNotIn(List<Date> values) {
			addCriterion("CRTIME not in", values, "crtime");
			return (Criteria) this;
		}

		public Criteria andCrtimeBetween(Date value1, Date value2) {
			addCriterion("CRTIME between", value1, value2, "crtime");
			return (Criteria) this;
		}

		public Criteria andCrtimeNotBetween(Date value1, Date value2) {
			addCriterion("CRTIME not between", value1, value2, "crtime");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("PRICE is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("PRICE is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Integer value) {
			addCriterion("PRICE =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Integer value) {
			addCriterion("PRICE <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Integer value) {
			addCriterion("PRICE >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("PRICE >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Integer value) {
			addCriterion("PRICE <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Integer value) {
			addCriterion("PRICE <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Integer> values) {
			addCriterion("PRICE in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Integer> values) {
			addCriterion("PRICE not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Integer value1, Integer value2) {
			addCriterion("PRICE between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("PRICE not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNull() {
			addCriterion("ISDELETED is null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNotNull() {
			addCriterion("ISDELETED is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedEqualTo(Byte value) {
			addCriterion("ISDELETED =", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotEqualTo(Byte value) {
			addCriterion("ISDELETED <>", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThan(Byte value) {
			addCriterion("ISDELETED >", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThanOrEqualTo(Byte value) {
			addCriterion("ISDELETED >=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThan(Byte value) {
			addCriterion("ISDELETED <", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThanOrEqualTo(Byte value) {
			addCriterion("ISDELETED <=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIn(List<Byte> values) {
			addCriterion("ISDELETED in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotIn(List<Byte> values) {
			addCriterion("ISDELETED not in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedBetween(Byte value1, Byte value2) {
			addCriterion("ISDELETED between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotBetween(Byte value1, Byte value2) {
			addCriterion("ISDELETED not between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andPasswordlevIsNull() {
			addCriterion("PASSWORDLEV is null");
			return (Criteria) this;
		}

		public Criteria andPasswordlevIsNotNull() {
			addCriterion("PASSWORDLEV is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordlevEqualTo(Integer value) {
			addCriterion("PASSWORDLEV =", value, "passwordlev");
			return (Criteria) this;
		}

		public Criteria andPasswordlevNotEqualTo(Integer value) {
			addCriterion("PASSWORDLEV <>", value, "passwordlev");
			return (Criteria) this;
		}

		public Criteria andPasswordlevGreaterThan(Integer value) {
			addCriterion("PASSWORDLEV >", value, "passwordlev");
			return (Criteria) this;
		}

		public Criteria andPasswordlevGreaterThanOrEqualTo(Integer value) {
			addCriterion("PASSWORDLEV >=", value, "passwordlev");
			return (Criteria) this;
		}

		public Criteria andPasswordlevLessThan(Integer value) {
			addCriterion("PASSWORDLEV <", value, "passwordlev");
			return (Criteria) this;
		}

		public Criteria andPasswordlevLessThanOrEqualTo(Integer value) {
			addCriterion("PASSWORDLEV <=", value, "passwordlev");
			return (Criteria) this;
		}

		public Criteria andPasswordlevIn(List<Integer> values) {
			addCriterion("PASSWORDLEV in", values, "passwordlev");
			return (Criteria) this;
		}

		public Criteria andPasswordlevNotIn(List<Integer> values) {
			addCriterion("PASSWORDLEV not in", values, "passwordlev");
			return (Criteria) this;
		}

		public Criteria andPasswordlevBetween(Integer value1, Integer value2) {
			addCriterion("PASSWORDLEV between", value1, value2, "passwordlev");
			return (Criteria) this;
		}

		public Criteria andPasswordlevNotBetween(Integer value1, Integer value2) {
			addCriterion("PASSWORDLEV not between", value1, value2, "passwordlev");
			return (Criteria) this;
		}

		public Criteria andViewdoclevelIsNull() {
			addCriterion("VIEWDOCLEVEL is null");
			return (Criteria) this;
		}

		public Criteria andViewdoclevelIsNotNull() {
			addCriterion("VIEWDOCLEVEL is not null");
			return (Criteria) this;
		}

		public Criteria andViewdoclevelEqualTo(Integer value) {
			addCriterion("VIEWDOCLEVEL =", value, "viewdoclevel");
			return (Criteria) this;
		}

		public Criteria andViewdoclevelNotEqualTo(Integer value) {
			addCriterion("VIEWDOCLEVEL <>", value, "viewdoclevel");
			return (Criteria) this;
		}

		public Criteria andViewdoclevelGreaterThan(Integer value) {
			addCriterion("VIEWDOCLEVEL >", value, "viewdoclevel");
			return (Criteria) this;
		}

		public Criteria andViewdoclevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("VIEWDOCLEVEL >=", value, "viewdoclevel");
			return (Criteria) this;
		}

		public Criteria andViewdoclevelLessThan(Integer value) {
			addCriterion("VIEWDOCLEVEL <", value, "viewdoclevel");
			return (Criteria) this;
		}

		public Criteria andViewdoclevelLessThanOrEqualTo(Integer value) {
			addCriterion("VIEWDOCLEVEL <=", value, "viewdoclevel");
			return (Criteria) this;
		}

		public Criteria andViewdoclevelIn(List<Integer> values) {
			addCriterion("VIEWDOCLEVEL in", values, "viewdoclevel");
			return (Criteria) this;
		}

		public Criteria andViewdoclevelNotIn(List<Integer> values) {
			addCriterion("VIEWDOCLEVEL not in", values, "viewdoclevel");
			return (Criteria) this;
		}

		public Criteria andViewdoclevelBetween(Integer value1, Integer value2) {
			addCriterion("VIEWDOCLEVEL between", value1, value2, "viewdoclevel");
			return (Criteria) this;
		}

		public Criteria andViewdoclevelNotBetween(Integer value1, Integer value2) {
			addCriterion("VIEWDOCLEVEL not between", value1, value2, "viewdoclevel");
			return (Criteria) this;
		}

		public Criteria andSupervisoridIsNull() {
			addCriterion("SUPERVISORID is null");
			return (Criteria) this;
		}

		public Criteria andSupervisoridIsNotNull() {
			addCriterion("SUPERVISORID is not null");
			return (Criteria) this;
		}

		public Criteria andSupervisoridEqualTo(Integer value) {
			addCriterion("SUPERVISORID =", value, "supervisorid");
			return (Criteria) this;
		}

		public Criteria andSupervisoridNotEqualTo(Integer value) {
			addCriterion("SUPERVISORID <>", value, "supervisorid");
			return (Criteria) this;
		}

		public Criteria andSupervisoridGreaterThan(Integer value) {
			addCriterion("SUPERVISORID >", value, "supervisorid");
			return (Criteria) this;
		}

		public Criteria andSupervisoridGreaterThanOrEqualTo(Integer value) {
			addCriterion("SUPERVISORID >=", value, "supervisorid");
			return (Criteria) this;
		}

		public Criteria andSupervisoridLessThan(Integer value) {
			addCriterion("SUPERVISORID <", value, "supervisorid");
			return (Criteria) this;
		}

		public Criteria andSupervisoridLessThanOrEqualTo(Integer value) {
			addCriterion("SUPERVISORID <=", value, "supervisorid");
			return (Criteria) this;
		}

		public Criteria andSupervisoridIn(List<Integer> values) {
			addCriterion("SUPERVISORID in", values, "supervisorid");
			return (Criteria) this;
		}

		public Criteria andSupervisoridNotIn(List<Integer> values) {
			addCriterion("SUPERVISORID not in", values, "supervisorid");
			return (Criteria) this;
		}

		public Criteria andSupervisoridBetween(Integer value1, Integer value2) {
			addCriterion("SUPERVISORID between", value1, value2, "supervisorid");
			return (Criteria) this;
		}

		public Criteria andSupervisoridNotBetween(Integer value1, Integer value2) {
			addCriterion("SUPERVISORID not between", value1, value2, "supervisorid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wcmuser
     *
     * @mbggenerated do_not_delete_during_merge Sat Feb 25 14:05:19 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}