package com.qheeshow.eway.service.model;

import com.qheeshow.eway.common.bean.BaseBean;
import java.util.Date;

public class User extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.USERID
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.STATUS
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.USERNAME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.PASSWORD
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.NICKNAME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.TRUENAME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.ADDRESS
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.TEL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.MOBILE
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.EMAIL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.REMINDERQUESTION
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private String reminderquestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.REMINDERANSWER
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private String reminderanswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.IFPUBMYINFO
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Byte ifpubmyinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.APPLYTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Date applytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.REGTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.LOGINTIMES
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Integer logintimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.LOGINTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Date logintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.LOGOUTTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Date logouttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.MSGINTERVAL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Short msginterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.VIEWINTERVAL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Short viewinterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.ATTRIBUTE
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private String attribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.CRUSER
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private String cruser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.CRTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Date crtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.PRICE
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.ISDELETED
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Byte isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.PASSWORDLEV
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Integer passwordlev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.VIEWDOCLEVEL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Integer viewdoclevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wcmuser.SUPERVISORID
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    private Integer supervisorid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.USERID
     *
     * @return the value of wcmuser.USERID
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.USERID
     *
     * @param userid the value for wcmuser.USERID
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.STATUS
     *
     * @return the value of wcmuser.STATUS
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.STATUS
     *
     * @param status the value for wcmuser.STATUS
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.USERNAME
     *
     * @return the value of wcmuser.USERNAME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.USERNAME
     *
     * @param username the value for wcmuser.USERNAME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.PASSWORD
     *
     * @return the value of wcmuser.PASSWORD
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.PASSWORD
     *
     * @param password the value for wcmuser.PASSWORD
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.NICKNAME
     *
     * @return the value of wcmuser.NICKNAME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.NICKNAME
     *
     * @param nickname the value for wcmuser.NICKNAME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.TRUENAME
     *
     * @return the value of wcmuser.TRUENAME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.TRUENAME
     *
     * @param truename the value for wcmuser.TRUENAME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.ADDRESS
     *
     * @return the value of wcmuser.ADDRESS
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.ADDRESS
     *
     * @param address the value for wcmuser.ADDRESS
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.TEL
     *
     * @return the value of wcmuser.TEL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.TEL
     *
     * @param tel the value for wcmuser.TEL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.MOBILE
     *
     * @return the value of wcmuser.MOBILE
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.MOBILE
     *
     * @param mobile the value for wcmuser.MOBILE
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.EMAIL
     *
     * @return the value of wcmuser.EMAIL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.EMAIL
     *
     * @param email the value for wcmuser.EMAIL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.REMINDERQUESTION
     *
     * @return the value of wcmuser.REMINDERQUESTION
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public String getReminderquestion() {
        return reminderquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.REMINDERQUESTION
     *
     * @param reminderquestion the value for wcmuser.REMINDERQUESTION
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setReminderquestion(String reminderquestion) {
        this.reminderquestion = reminderquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.REMINDERANSWER
     *
     * @return the value of wcmuser.REMINDERANSWER
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public String getReminderanswer() {
        return reminderanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.REMINDERANSWER
     *
     * @param reminderanswer the value for wcmuser.REMINDERANSWER
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setReminderanswer(String reminderanswer) {
        this.reminderanswer = reminderanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.IFPUBMYINFO
     *
     * @return the value of wcmuser.IFPUBMYINFO
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Byte getIfpubmyinfo() {
        return ifpubmyinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.IFPUBMYINFO
     *
     * @param ifpubmyinfo the value for wcmuser.IFPUBMYINFO
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setIfpubmyinfo(Byte ifpubmyinfo) {
        this.ifpubmyinfo = ifpubmyinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.APPLYTIME
     *
     * @return the value of wcmuser.APPLYTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.APPLYTIME
     *
     * @param applytime the value for wcmuser.APPLYTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.REGTIME
     *
     * @return the value of wcmuser.REGTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.REGTIME
     *
     * @param regtime the value for wcmuser.REGTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.LOGINTIMES
     *
     * @return the value of wcmuser.LOGINTIMES
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Integer getLogintimes() {
        return logintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.LOGINTIMES
     *
     * @param logintimes the value for wcmuser.LOGINTIMES
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setLogintimes(Integer logintimes) {
        this.logintimes = logintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.LOGINTIME
     *
     * @return the value of wcmuser.LOGINTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Date getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.LOGINTIME
     *
     * @param logintime the value for wcmuser.LOGINTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.LOGOUTTIME
     *
     * @return the value of wcmuser.LOGOUTTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Date getLogouttime() {
        return logouttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.LOGOUTTIME
     *
     * @param logouttime the value for wcmuser.LOGOUTTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setLogouttime(Date logouttime) {
        this.logouttime = logouttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.MSGINTERVAL
     *
     * @return the value of wcmuser.MSGINTERVAL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Short getMsginterval() {
        return msginterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.MSGINTERVAL
     *
     * @param msginterval the value for wcmuser.MSGINTERVAL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setMsginterval(Short msginterval) {
        this.msginterval = msginterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.VIEWINTERVAL
     *
     * @return the value of wcmuser.VIEWINTERVAL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Short getViewinterval() {
        return viewinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.VIEWINTERVAL
     *
     * @param viewinterval the value for wcmuser.VIEWINTERVAL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setViewinterval(Short viewinterval) {
        this.viewinterval = viewinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.ATTRIBUTE
     *
     * @return the value of wcmuser.ATTRIBUTE
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.ATTRIBUTE
     *
     * @param attribute the value for wcmuser.ATTRIBUTE
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.CRUSER
     *
     * @return the value of wcmuser.CRUSER
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public String getCruser() {
        return cruser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.CRUSER
     *
     * @param cruser the value for wcmuser.CRUSER
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setCruser(String cruser) {
        this.cruser = cruser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.CRTIME
     *
     * @return the value of wcmuser.CRTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Date getCrtime() {
        return crtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.CRTIME
     *
     * @param crtime the value for wcmuser.CRTIME
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setCrtime(Date crtime) {
        this.crtime = crtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.PRICE
     *
     * @return the value of wcmuser.PRICE
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.PRICE
     *
     * @param price the value for wcmuser.PRICE
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.ISDELETED
     *
     * @return the value of wcmuser.ISDELETED
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Byte getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.ISDELETED
     *
     * @param isdeleted the value for wcmuser.ISDELETED
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setIsdeleted(Byte isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.PASSWORDLEV
     *
     * @return the value of wcmuser.PASSWORDLEV
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Integer getPasswordlev() {
        return passwordlev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.PASSWORDLEV
     *
     * @param passwordlev the value for wcmuser.PASSWORDLEV
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setPasswordlev(Integer passwordlev) {
        this.passwordlev = passwordlev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.VIEWDOCLEVEL
     *
     * @return the value of wcmuser.VIEWDOCLEVEL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Integer getViewdoclevel() {
        return viewdoclevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.VIEWDOCLEVEL
     *
     * @param viewdoclevel the value for wcmuser.VIEWDOCLEVEL
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setViewdoclevel(Integer viewdoclevel) {
        this.viewdoclevel = viewdoclevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wcmuser.SUPERVISORID
     *
     * @return the value of wcmuser.SUPERVISORID
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public Integer getSupervisorid() {
        return supervisorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wcmuser.SUPERVISORID
     *
     * @param supervisorid the value for wcmuser.SUPERVISORID
     *
     * @mbggenerated Sat Feb 25 14:07:05 CST 2017
     */
    public void setSupervisorid(Integer supervisorid) {
        this.supervisorid = supervisorid;
    }
}