package com.qheeshow.eway.service.model;

import com.qheeshow.eway.common.bean.BaseBean;
import java.util.Date;

public class XWClassInfo extends BaseBean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xwcmclassinfo.CLASSINFOID
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	private Integer classinfoid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xwcmclassinfo.CLASSORDER
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	private Integer classorder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xwcmclassinfo.CNAME
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	private String cname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xwcmclassinfo.CDESC
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	private String cdesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xwcmclassinfo.PARENTID
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	private Integer parentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xwcmclassinfo.ROOTID
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	private Integer rootid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xwcmclassinfo.CRUSER
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	private String cruser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xwcmclassinfo.CRTIME
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	private Date crtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xwcmclassinfo.CCODE
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	private String ccode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xwcmclassinfo.CLASSINFOID
	 * @return  the value of xwcmclassinfo.CLASSINFOID
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public Integer getClassinfoid() {
		return classinfoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xwcmclassinfo.CLASSINFOID
	 * @param classinfoid  the value for xwcmclassinfo.CLASSINFOID
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public void setClassinfoid(Integer classinfoid) {
		this.classinfoid = classinfoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xwcmclassinfo.CLASSORDER
	 * @return  the value of xwcmclassinfo.CLASSORDER
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public Integer getClassorder() {
		return classorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xwcmclassinfo.CLASSORDER
	 * @param classorder  the value for xwcmclassinfo.CLASSORDER
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public void setClassorder(Integer classorder) {
		this.classorder = classorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xwcmclassinfo.CNAME
	 * @return  the value of xwcmclassinfo.CNAME
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public String getCname() {
		return cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xwcmclassinfo.CNAME
	 * @param cname  the value for xwcmclassinfo.CNAME
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public void setCname(String cname) {
		this.cname = cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xwcmclassinfo.CDESC
	 * @return  the value of xwcmclassinfo.CDESC
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public String getCdesc() {
		return cdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xwcmclassinfo.CDESC
	 * @param cdesc  the value for xwcmclassinfo.CDESC
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public void setCdesc(String cdesc) {
		this.cdesc = cdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xwcmclassinfo.PARENTID
	 * @return  the value of xwcmclassinfo.PARENTID
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public Integer getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xwcmclassinfo.PARENTID
	 * @param parentid  the value for xwcmclassinfo.PARENTID
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xwcmclassinfo.ROOTID
	 * @return  the value of xwcmclassinfo.ROOTID
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public Integer getRootid() {
		return rootid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xwcmclassinfo.ROOTID
	 * @param rootid  the value for xwcmclassinfo.ROOTID
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public void setRootid(Integer rootid) {
		this.rootid = rootid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xwcmclassinfo.CRUSER
	 * @return  the value of xwcmclassinfo.CRUSER
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public String getCruser() {
		return cruser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xwcmclassinfo.CRUSER
	 * @param cruser  the value for xwcmclassinfo.CRUSER
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public void setCruser(String cruser) {
		this.cruser = cruser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xwcmclassinfo.CRTIME
	 * @return  the value of xwcmclassinfo.CRTIME
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public Date getCrtime() {
		return crtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xwcmclassinfo.CRTIME
	 * @param crtime  the value for xwcmclassinfo.CRTIME
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public void setCrtime(Date crtime) {
		this.crtime = crtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xwcmclassinfo.CCODE
	 * @return  the value of xwcmclassinfo.CCODE
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public String getCcode() {
		return ccode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xwcmclassinfo.CCODE
	 * @param ccode  the value for xwcmclassinfo.CCODE
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	public void setCcode(String ccode) {
		this.ccode = ccode;
	}
}