package com.qheeshow.eway.service.dao;

import com.qheeshow.eway.service.model.Document;
import com.qheeshow.eway.service.model.DocumentExample;
import com.qheeshow.eway.service.model.DocumentWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocumentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	int countByExample(DocumentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	int deleteByExample(DocumentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	int insert(DocumentWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	int insertSelective(DocumentWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	List<DocumentWithBLOBs> selectByExampleWithBLOBs(DocumentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	List<Document> selectByExample(DocumentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	DocumentWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	int updateByExampleSelective(@Param("record") DocumentWithBLOBs record, @Param("example") DocumentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") DocumentWithBLOBs record, @Param("example") DocumentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	int updateByExample(@Param("record") Document record, @Param("example") DocumentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	int updateByPrimaryKeySelective(DocumentWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(DocumentWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document
	 * @mbggenerated  Sun Feb 26 11:00:39 CST 2017
	 */
	int updateByPrimaryKey(Document record);
}