package com.qheeshow.eway.service.dao;

import com.qheeshow.eway.service.model.DocumentEnroll;
import com.qheeshow.eway.service.model.DocumentEnrollExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocumentEnrollMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document_enroll
	 * @mbggenerated  Sun Feb 26 10:55:17 CST 2017
	 */
	int countByExample(DocumentEnrollExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document_enroll
	 * @mbggenerated  Sun Feb 26 10:55:17 CST 2017
	 */
	int deleteByExample(DocumentEnrollExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document_enroll
	 * @mbggenerated  Sun Feb 26 10:55:17 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document_enroll
	 * @mbggenerated  Sun Feb 26 10:55:17 CST 2017
	 */
	int insert(DocumentEnroll record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document_enroll
	 * @mbggenerated  Sun Feb 26 10:55:17 CST 2017
	 */
	int insertSelective(DocumentEnroll record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document_enroll
	 * @mbggenerated  Sun Feb 26 10:55:17 CST 2017
	 */
	List<DocumentEnroll> selectByExample(DocumentEnrollExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document_enroll
	 * @mbggenerated  Sun Feb 26 10:55:17 CST 2017
	 */
	DocumentEnroll selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document_enroll
	 * @mbggenerated  Sun Feb 26 10:55:17 CST 2017
	 */
	int updateByExampleSelective(@Param("record") DocumentEnroll record,
			@Param("example") DocumentEnrollExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document_enroll
	 * @mbggenerated  Sun Feb 26 10:55:17 CST 2017
	 */
	int updateByExample(@Param("record") DocumentEnroll record, @Param("example") DocumentEnrollExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document_enroll
	 * @mbggenerated  Sun Feb 26 10:55:17 CST 2017
	 */
	int updateByPrimaryKeySelective(DocumentEnroll record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_document_enroll
	 * @mbggenerated  Sun Feb 26 10:55:17 CST 2017
	 */
	int updateByPrimaryKey(DocumentEnroll record);
}