package com.qheeshow.eway.service.dao;

import com.qheeshow.eway.service.model.File;
import com.qheeshow.eway.service.model.FileExample;
import com.qheeshow.eway.service.model.FileWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	int countByExample(FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	int deleteByExample(FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	int insert(FileWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	int insertSelective(FileWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	List<FileWithBLOBs> selectByExampleWithBLOBs(FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	List<File> selectByExample(FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	FileWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	int updateByExampleSelective(@Param("record") FileWithBLOBs record, @Param("example") FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") FileWithBLOBs record, @Param("example") FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	int updateByExample(@Param("record") File record, @Param("example") FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	int updateByPrimaryKeySelective(FileWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(FileWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 * @mbggenerated  Sun Feb 26 16:30:28 CST 2017
	 */
	int updateByPrimaryKey(File record);
}