package com.qheeshow.eway.service.dao;

import com.qheeshow.eway.service.model.User;
import com.qheeshow.eway.service.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	int countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	int deleteByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	User selectByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	int updateByExample(@Param("record") User record, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wcmuser
	 * @mbggenerated  Sat Feb 25 14:07:05 CST 2017
	 */
	int updateByPrimaryKey(User record);
}