package com.qheeshow.eway.service.dao;

import com.qheeshow.eway.service.model.XWClassInfo;
import com.qheeshow.eway.service.model.XWClassInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XWClassInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xwcmclassinfo
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	int countByExample(XWClassInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xwcmclassinfo
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	int deleteByExample(XWClassInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xwcmclassinfo
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	int deleteByPrimaryKey(Integer classinfoid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xwcmclassinfo
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	int insert(XWClassInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xwcmclassinfo
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	int insertSelective(XWClassInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xwcmclassinfo
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	List<XWClassInfo> selectByExample(XWClassInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xwcmclassinfo
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	XWClassInfo selectByPrimaryKey(Integer classinfoid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xwcmclassinfo
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	int updateByExampleSelective(@Param("record") XWClassInfo record, @Param("example") XWClassInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xwcmclassinfo
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	int updateByExample(@Param("record") XWClassInfo record, @Param("example") XWClassInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xwcmclassinfo
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	int updateByPrimaryKeySelective(XWClassInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xwcmclassinfo
	 * @mbggenerated  Sun Mar 05 18:53:12 CST 2017
	 */
	int updateByPrimaryKey(XWClassInfo record);
}