//项目所属行业rootid
classinfo_rootid_industry=20;
//项目所属地域rootid
classinfo_rootid_area=21;
//项目融资额度rootid
classinfo_rootid_financing_limit=31;
//项目标签
classinfo_rootid_tag=1;
//融资阶段
classinfo_rootid_stage=44;
//项目根路径
root_path="http://127.0.0.1:8092/index";